#!/bin/sh
BOOST_CPPFLAGS="-I/usr/local/include -I/opt/local/include"               \
LDFLAGS="-lintl -L/usr/local/lib -L/opt/local/lib"                       \
CFLAGS="-I/usr/local/include/ -I/opt/local/include"                      \
CPPFLAGS="-I/usr/local/include/ -I/opt/local/include                     \
-I/usr/local/include/osxfuse" ./configure --disable-nls                  \
--with-boost-system=boost_system                                         \
--with-boost-filesystem=boost_filesystem                                 \
--with-boost-serialization=boost_serialization --prefix="$PWD/../Youcrypt" --program-prefix=yc-
