Youcrypt/EncFS: BlockFileIO.cpp File Reference
BlockFileIO.cpp File Reference
#include "BlockFileIO.h"
#include "MemoryPool.h"
#include <cstring>
#include <rlog/rlog.h>
#include "i18n.h"
Functions
template<typename Type >
Type min (Type A, Type B)
static void clearCache (IORequest &req, int blockSize)
Function Documentation
static void clearCache (IORequest & req, int blockSize) static
References IORequest::data, and IORequest::dataLen.
Referenced by BlockFileIO::cacheReadOneBlock(), BlockFileIO::cacheWriteOneBlock(), and BlockFileIO::~BlockFileIO().
template<typename Type > Type min (Type A, Type B) inline
Referenced by BlockFileIO::read(), and BlockFileIO::write().