Youcrypt/EncFS: ConfigVar.h File Reference
ConfigVar.h File Reference
#include <string>
#include <boost/shared_ptr.hpp>
Classes
class ConfigVar
struct ConfigVar::ConfigVarData
Functions
ConfigVar & operator<< (ConfigVar &, bool)
ConfigVar & operator<< (ConfigVar &, int)
ConfigVar & operator<< (ConfigVar &, const std::string &str)
const ConfigVar & operator>> (const ConfigVar &, bool &)
const ConfigVar & operator>> (const ConfigVar &, int &)
const ConfigVar & operator>> (const ConfigVar &, std::string &str)
Function Documentation
ConfigVar& operator<< (ConfigVar & , bool)
References ConfigVar::writeInt().
ConfigVar& operator<< (ConfigVar & , int)
References ConfigVar::writeInt().
ConfigVar& operator<< (ConfigVar & , const std::string & str)
References ConfigVar::writeString().
const ConfigVar& operator>> (const ConfigVar & , bool &)
References ConfigVar::readInt().
const ConfigVar& operator>> (const ConfigVar & , int &)
References ConfigVar::readInt().
const ConfigVar& operator>> (const ConfigVar & , std::string & str)
References ConfigVar::read(), and ConfigVar::readInt().