Youcrypt/EncFS: ConfigVar.cpp File Reference
ConfigVar.cpp File Reference
#include "ConfigVar.h"
#include <rlog/rlog.h>
#include <cstring>
Functions
int MIN (int a, int b)
ConfigVar & operator<< (ConfigVar &src, bool value)
ConfigVar & operator<< (ConfigVar &src, int var)
ConfigVar & operator<< (ConfigVar &src, const std::string &str)
const ConfigVar & operator>> (const ConfigVar &src, bool &result)
const ConfigVar & operator>> (const ConfigVar &src, int &result)
const ConfigVar & operator>> (const ConfigVar &src, std::string &result)
Function Documentation
int MIN (int a, int b) inline
ConfigVar& operator<< (ConfigVar & src, bool value)
References ConfigVar::writeInt().
ConfigVar& operator<< (ConfigVar & src, int var)
References ConfigVar::writeInt().
ConfigVar& operator<< (ConfigVar & src, const std::string & str)
References ConfigVar::writeString().
const ConfigVar& operator>> (const ConfigVar & src, bool & result)
References ConfigVar::readInt().
const ConfigVar& operator>> (const ConfigVar & src, int & result)
References ConfigVar::readInt().
const ConfigVar& operator>> (const ConfigVar & src, std::string & result)
References ConfigVar::read(), and ConfigVar::readInt().