Youcrypt/EncFS: FileUtils.cpp File Reference
FileUtils.cpp File Reference
#include "encfs.h"
#include "config.h"
#include "readpassphrase.h"
#include "autosprintf.h"
#include "FileUtils.h"
#include "ConfigReader.h"
#include "FSConfig.h"
#include "DirNode.h"
#include "Cipher.h"
#include "StreamNameIO.h"
#include "BlockNameIO.h"
#include "NullNameIO.h"
#include "YCNameIO.h"
#include "Context.h"
#include <rlog/rlog.h>
#include <rlog/Error.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/wait.h>
#include <fcntl.h>
#include <unistd.h>
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <cerrno>
#include <cstring>
#include <iostream>
#include <sstream>
#include "i18n.h"
#include <boost/version.hpp>
#include <boost/filesystem/fstream.hpp>
#include <boost/archive/xml_iarchive.hpp>
#include <boost/archive/xml_oarchive.hpp>
#include <boost/serialization/split_free.hpp>
#include <boost/serialization/vector.hpp>
#include <boost/serialization/binary_object.hpp>
#include <boost/serialization/string.hpp>
#include "boost-versioning.h"
Classes
struct ConfigInfo
Namespaces
namespace boost
namespace boost::serialization
Macros
#define _BSD_SOURCE
#define RLOG_SECTION
Functions
template<class Archive >
void boost::serialization::save (Archive &ar, const EncFSConfig &cfg, unsigned int version)
template<class Archive >
void boost::serialization::load (Archive &ar, EncFSConfig &cfg, unsigned int version)
template<class Archive >
void boost::serialization::serialize (Archive &ar, EncFSConfig &cfg, unsigned int version)
template<class Archive >
void boost::serialization::serialize (Archive &ar, Interface &i, const unsigned int version)
bool fileExists (const char *fileName)
bool isDirectory (const char *fileName)
bool isAbsolutePath (const char *fileName)
const char * lastPathElement (const char *name)
std::string parentDirectory (const std::string &path)
bool userAllowMkdir (const char *path, mode_t mode)
ConfigType readConfig_load (ConfigInfo *nm, const char *path, const boost::shared_ptr< EncFSConfig > &config)
ConfigType readConfig (const string &rootDir, const boost::shared_ptr< EncFSConfig > &config)
bool readV6Config (const char *configFile, const boost::shared_ptr< EncFSConfig > &config, ConfigInfo *info)
bool readV5Config (const char *configFile, const boost::shared_ptr< EncFSConfig > &config, ConfigInfo *info)
bool readV4Config (const char *configFile, const boost::shared_ptr< EncFSConfig > &config, ConfigInfo *info)
bool saveConfig (ConfigType type, const string &rootDir, const boost::shared_ptr< EncFSConfig > &config)
bool writeV6Config (const char *configFile, const boost::shared_ptr< EncFSConfig > &config)
std::ostream & operator<< (std::ostream &st, const EncFSConfig &cfg)
std::istream & operator>> (std::istream &st, EncFSConfig &cfg)
bool writeV5Config (const char *configFile, const boost::shared_ptr< EncFSConfig > &config)
bool writeV4Config (const char *configFile, const boost::shared_ptr< EncFSConfig > &config)
Cipher::CipherAlgorithm findCipherAlgorithm (const char *name, int keySize)
static Cipher::CipherAlgorithm selectCipherAlgorithm ()
static Interface selectNameCoding ()
static int selectKeySize (const Cipher::CipherAlgorithm &alg)
static int selectBlockSize (const Cipher::CipherAlgorithm &alg)
static bool boolDefaultNo (const char *prompt)
static void selectBlockMAC (int *macBytes, int *macRandBytes)
static bool boolDefaultYes (const char *prompt)
static bool selectUniqueIV ()
static bool selectChainedIV ()
static bool selectExternalChainedIV ()
static bool selectZeroBlockPassThrough ()
RootPtr createV6Config (EncFS_Context *ctx, const shared_ptr< EncFS_Opts > &opts)
void showFSInfo (const boost::shared_ptr< EncFSConfig > &config)
std::string readPassword (int FD)
RootPtr initFS (EncFS_Context *ctx, const shared_ptr< EncFS_Opts > &opts)
int remountFS (EncFS_Context *ctx)
Variables
static const int DefaultBlockSize = 1024
static const int MaxPassBuf = 512
static const int NormalKDFDuration = 500
static const int ParanoiaKDFDuration = 3000
static const char ENCFS_ENV_ROOTDIR [] = "encfs_root"
static const char ENCFS_ENV_STDOUT [] = "encfs_stdout"
static const char ENCFS_ENV_STDERR [] = "encfs_stderr"
static int V5SubVersion = 20040813
static int V5SubVersionDefault = 0
const int V6SubVersion = 20100713
const int YCSubVersion = 0
struct ConfigInfo ConfigFileMapping []
Macro Definition Documentation
#define _BSD_SOURCE
#define RLOG_SECTION
Function Documentation
static bool boolDefaultNo (const char * prompt) static
References _.
Referenced by selectBlockMAC(), and selectExternalChainedIV().
static bool boolDefaultYes (const char * prompt) static
References _.
Referenced by selectChainedIV(), selectUniqueIV(), and selectZeroBlockPassThrough().
RootPtr createV6Config (EncFS_Context * ctx, const shared_ptr< EncFS_Opts > & opts)
References _, Config_Paranoia, Config_Prompt, Config_Standard, Config_YC, YCNameIO::CurrentInterface(), BlockNameIO::CurrentInterface(), DefaultBlockSize, findCipherAlgorithm(), Cipher::CipherAlgorithm::name, NameIO::New(), Cipher::New(), NormalKDFDuration, ParanoiaKDFDuration, saveConfig(), selectBlockMAC(), selectBlockSize(), selectChainedIV(), selectCipherAlgorithm(), selectExternalChainedIV(), selectKeySize(), selectNameCoding(), selectUniqueIV(), selectZeroBlockPassThrough(), showFSInfo(), and V6SubVersion.
Referenced by initFS().
bool fileExists (const char * fileName)
Referenced by readConfig().
Cipher::CipherAlgorithm findCipherAlgorithm (const char * name, int keySize)
References Cipher::GetAlgorithmList().
Referenced by youcrypt::YoucryptFolder::createAtPath(), and createV6Config().
RootPtr initFS (EncFS_Context * ctx, const shared_ptr< EncFS_Opts > & opts)
References _, Config_None, createV6Config(), NameIO::New(), and readConfig().
Referenced by initRootInfo(), main(), and remountFS().
bool isAbsolutePath (const char * fileName)
Referenced by processArgs().
bool isDirectory (const char * fileName)
Referenced by checkDir(), DirNode::genRenameList(), processArgs(), DirNode::rename(), and showcruft().
const char* lastPathElement (const char * name)
Referenced by processArgs().
std::ostream& operator<< (std::ostream & st, const EncFSConfig & cfg)
std::istream& operator>> (std::istream & st, EncFSConfig & cfg)
std::string parentDirectory (const std::string & path)
Referenced by encfs_mkdir(), and FileNode::plaintextParent().
ConfigType readConfig (const string & rootDir, const boost::shared_ptr< EncFSConfig > & config)
References Config_None, ConfigFileMapping, ConfigInfo::environmentOverride, fileExists(), ConfigInfo::fileName, and readConfig_load().
Referenced by youcrypt::YoucryptFolder::addCredential(), do_chpasswd(), initFS(), youcrypt::YoucryptFolder::loadConfigAtPath(), and showInfo().
ConfigType readConfig_load (ConfigInfo * nm, const char * path, const boost::shared_ptr< EncFSConfig > & config)
References _, Config_None, ConfigInfo::loadFunc, and ConfigInfo::type.
Referenced by readConfig().
std::string readPassword (int FD)
Referenced by EncFSConfig::getUserKey().
bool readV4Config (const char * configFile, const boost::shared_ptr< EncFSConfig > & config, ConfigInfo * info)
References ConfigInfo::defaultSubVersion, and ConfigReader::load().
bool readV5Config (const char * configFile, const boost::shared_ptr< EncFSConfig > & config, ConfigInfo * info)
References _, ConfigInfo::currentSubVersion, ConfigInfo::defaultSubVersion, and ConfigReader::load().
bool readV6Config (const char * configFile, const boost::shared_ptr< EncFSConfig > & config, ConfigInfo * info)
int remountFS (EncFS_Context * ctx)
References _, initFS(), EncFS_Context::opts, and EncFS_Context::setRoot().
Referenced by EncFS_Context::getRoot().
bool saveConfig (ConfigType type, const string & rootDir, const boost::shared_ptr< EncFSConfig > & config)
References ConfigFileMapping, ConfigInfo::environmentOverride, ConfigInfo::fileName, ConfigInfo::saveFunc, and ConfigInfo::type.
Referenced by youcrypt::YoucryptFolder::addCredential(), youcrypt::YoucryptFolder::createAtPath(), createV6Config(), and do_chpasswd().
static void selectBlockMAC (int * macBytes, int * macRandBytes) static
References _, and boolDefaultNo().
Referenced by createV6Config().
static int selectBlockSize (const Cipher::CipherAlgorithm & alg) static
References _, Cipher::CipherAlgorithm::blockSize, Range::closest(), DefaultBlockSize, Range::inc(), Range::max(), and Range::min().
Referenced by createV6Config().
static bool selectChainedIV () static
References _, and boolDefaultYes().
Referenced by createV6Config().
static Cipher::CipherAlgorithm selectCipherAlgorithm () static
References _, Cipher::GetAlgorithmList(), gettext, and Cipher::CipherAlgorithm::name.
Referenced by createV6Config().
static bool selectExternalChainedIV () static
References _, and boolDefaultNo().
Referenced by createV6Config().
static int selectKeySize (const Cipher::CipherAlgorithm & alg) static
References _, Range::closest(), Range::inc(), Cipher::CipherAlgorithm::keyLength, Range::max(), and Range::min().
Referenced by createV6Config().
static Interface selectNameCoding () static
References _, NameIO::GetAlgorithmList(), and gettext.
Referenced by createV6Config().
static bool selectUniqueIV () static
References _, and boolDefaultYes().
Referenced by createV6Config().
static bool selectZeroBlockPassThrough () static
References _, and boolDefaultYes().
Referenced by createV6Config().
void showFSInfo (const boost::shared_ptr< EncFSConfig > & config)
References _, rel::Interface::age(), rel::Interface::current(), NameIO::New(), Cipher::New(), and rel::Interface::revision().
Referenced by createV6Config(), and showInfo().
bool userAllowMkdir (const char * path, mode_t mode)
References _.
Referenced by cmd_export(), and processArgs().
bool writeV4Config (const char * configFile, const boost::shared_ptr< EncFSConfig > & config)
References ConfigReader::save().
bool writeV5Config (const char * configFile, const boost::shared_ptr< EncFSConfig > & config)
References ConfigReader::save().
bool writeV6Config (const char * configFile, const boost::shared_ptr< EncFSConfig > & config)
Variable Documentation
struct ConfigInfo ConfigFileMapping[]
Referenced by readConfig(), and saveConfig().
const int DefaultBlockSize = 1024 static
Referenced by createV6Config(), and selectBlockSize().
const char ENCFS_ENV_ROOTDIR[] = "encfs_root" static
Referenced by EncFSConfig::getUserKey().
const char ENCFS_ENV_STDERR[] = "encfs_stderr" static
Referenced by EncFSConfig::getUserKey().
const char ENCFS_ENV_STDOUT[] = "encfs_stdout" static
Referenced by EncFSConfig::getUserKey().
const int MaxPassBuf = 512 static
Referenced by EncFSConfig::getNewUserKey(), and EncFSConfig::getUserKey().
const int NormalKDFDuration = 500 static
Referenced by createV6Config(), and boost::serialization::load().
const int ParanoiaKDFDuration = 3000 static
Referenced by createV6Config().
int V5SubVersion = 20040813 static
Referenced by boost::serialization::load().
int V5SubVersionDefault = 0 static
const int V6SubVersion = 20100713
Referenced by createV6Config(), and boost::serialization::save().
const int YCSubVersion = 0