Youcrypt/EncFS: FileNode.cpp File Reference
FileNode.cpp File Reference
#include "encfs.h"
#include <errno.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
#include <cstring>
#include "config.h"
#include "FileNode.h"
#include "FileUtils.h"
#include "Cipher.h"
#include "CipherFileIO.h"
#include "RawFileIO.h"
#include "MACFileIO.h"
#include "DirNode.h"
#include "FileIO.h"
#include "MemoryPool.h"
#include "Mutex.h"
#include <rlog/rlog.h>
#include <rlog/Error.h>
Functions
bool _should_ignore (const char *plainText, boost::shared_ptr< EncFSConfig > &config)
static bool setIV (const shared_ptr< FileIO > &io, uint64_t iv)
Variables
static RLogChannel * Info = DEF_CHANNEL("info/FileNode", Log_Info)
Function Documentation
bool _should_ignore (const char * plainText, boost::shared_ptr< EncFSConfig > & config)
Referenced by FileNode::FileNode().
static bool setIV (const shared_ptr< FileIO > & io, uint64_t iv) static
Referenced by FileNode::setName().
Variable Documentation
RLogChannel* Info = DEF_CHANNEL("info/FileNode", Log_Info) static
Referenced by FileNode::write().