Youcrypt/EncFS: FileUtils.h File Reference
FileUtils.h File Reference
#include "encfs.h"
#include "Interface.h"
#include "CipherKey.h"
#include "FSConfig.h"
Classes
struct EncFS_Root
struct EncFS_Opts
Typedefs
typedef boost::shared_ptr
< EncFS_Root > RootPtr
Enumerations
enum ConfigMode { Config_Prompt, Config_Standard, Config_Paranoia }
Functions
bool fileExists (const char *fileName)
bool isDirectory (const char *fileName)
bool isAbsolutePath (const char *fileName)
const char * lastPathElement (const char *name)
std::string parentDirectory (const std::string &path)
bool userAllowMkdir (const char *dirPath, mode_t mode)
ConfigType readConfig (const std::string &rootDir, const boost::shared_ptr< EncFSConfig > &config)
bool saveConfig (ConfigType type, const std::string &rootdir, const boost::shared_ptr< EncFSConfig > &config)
RootPtr initFS (EncFS_Context *ctx, const boost::shared_ptr< EncFS_Opts > &opts)
RootPtr createV6Config (EncFS_Context *ctx, const boost::shared_ptr< EncFS_Opts > &opts)
void showFSInfo (const boost::shared_ptr< EncFSConfig > &config)
bool readV4Config (const char *configFile, const boost::shared_ptr< EncFSConfig > &config, struct ConfigInfo *)
bool writeV4Config (const char *configFile, const boost::shared_ptr< EncFSConfig > &config)
bool readV5Config (const char *configFile, const boost::shared_ptr< EncFSConfig > &config, struct ConfigInfo *)
bool writeV5Config (const char *configFile, const boost::shared_ptr< EncFSConfig > &config)
bool readV6Config (const char *configFile, const boost::shared_ptr< EncFSConfig > &config, struct ConfigInfo *)
bool writeV6Config (const char *configFile, const boost::shared_ptr< EncFSConfig > &config)
Typedef Documentation
typedef boost::shared_ptr<EncFS_Root> RootPtr
Enumeration Type Documentation
enum ConfigMode
Enumerator:
Config_Prompt
Config_Standard
Config_Paranoia
Function Documentation
RootPtr createV6Config (EncFS_Context * ctx, const boost::shared_ptr< EncFS_Opts > & opts)
bool fileExists (const char * fileName)
Referenced by readConfig().
RootPtr initFS (EncFS_Context * ctx, const boost::shared_ptr< EncFS_Opts > & opts)
bool isAbsolutePath (const char * fileName)
Referenced by processArgs().
bool isDirectory (const char * fileName)
Referenced by checkDir(), DirNode::genRenameList(), processArgs(), DirNode::rename(), and showcruft().
const char* lastPathElement (const char * name)
Referenced by processArgs().
std::string parentDirectory (const std::string & path)
Referenced by encfs_mkdir(), and FileNode::plaintextParent().
ConfigType readConfig (const std::string & rootDir, const boost::shared_ptr< EncFSConfig > & config)
References Config_None, ConfigFileMapping, ConfigInfo::environmentOverride, fileExists(), ConfigInfo::fileName, and readConfig_load().
Referenced by youcrypt::YoucryptFolder::addCredential(), do_chpasswd(), initFS(), youcrypt::YoucryptFolder::loadConfigAtPath(), and showInfo().
bool readV4Config (const char * configFile, const boost::shared_ptr< EncFSConfig > & config, struct ConfigInfo *)
References ConfigInfo::defaultSubVersion, and ConfigReader::load().
bool readV5Config (const char * configFile, const boost::shared_ptr< EncFSConfig > & config, struct ConfigInfo *)
References _, ConfigInfo::currentSubVersion, ConfigInfo::defaultSubVersion, and ConfigReader::load().
bool readV6Config (const char * configFile, const boost::shared_ptr< EncFSConfig > & config, struct ConfigInfo *)
bool saveConfig (ConfigType type, const std::string & rootdir, const boost::shared_ptr< EncFSConfig > & config)
References ConfigFileMapping, ConfigInfo::environmentOverride, ConfigInfo::fileName, ConfigInfo::saveFunc, and ConfigInfo::type.
Referenced by youcrypt::YoucryptFolder::addCredential(), youcrypt::YoucryptFolder::createAtPath(), createV6Config(), and do_chpasswd().
void showFSInfo (const boost::shared_ptr< EncFSConfig > & config)
References _, rel::Interface::age(), rel::Interface::current(), NameIO::New(), Cipher::New(), and rel::Interface::revision().
Referenced by createV6Config(), and showInfo().
bool userAllowMkdir (const char * dirPath, mode_t mode)
References _.
Referenced by cmd_export(), and processArgs().
bool writeV4Config (const char * configFile, const boost::shared_ptr< EncFSConfig > & config)
References ConfigReader::save().
bool writeV5Config (const char * configFile, const boost::shared_ptr< EncFSConfig > & config)
References ConfigReader::save().
bool writeV6Config (const char * configFile, const boost::shared_ptr< EncFSConfig > & config)