Youcrypt/EncFS: Interface.h File Reference
Interface.h File Reference
#include <string>
Classes
class rel::Interface
Namespaces
namespace rel
Functions
ConfigVar & operator<< (ConfigVar &, const rel::Interface &)
const ConfigVar & operator>> (const ConfigVar &, rel::Interface &)
bool operator< (const rel::Interface &A, const rel::Interface &B)
bool operator> (const rel::Interface &A, const rel::Interface &B)
bool operator<= (const rel::Interface &A, const rel::Interface &B)
bool operator>= (const rel::Interface &A, const rel::Interface &B)
bool operator== (const rel::Interface &A, const rel::Interface &B)
bool operator!= (const rel::Interface &A, const rel::Interface &B)
Function Documentation
bool operator!= (const rel::Interface & A, const rel::Interface & B)
References rel::Interface::age(), rel::Interface::current(), rel::Interface::name(), and rel::Interface::revision().
bool operator< (const rel::Interface & A, const rel::Interface & B)
References diffSum(), EqualVersion, and rel::Interface::name().
ConfigVar& operator<< (ConfigVar & , const rel::Interface &)
References rel::Interface::age(), rel::Interface::current(), rel::Interface::name(), and rel::Interface::revision().
bool operator<= (const rel::Interface & A, const rel::Interface & B)
References diffSum(), EqualVersion, and rel::Interface::name().
bool operator== (const rel::Interface & A, const rel::Interface & B)
References rel::Interface::age(), rel::Interface::current(), rel::Interface::name(), and rel::Interface::revision().
bool operator> (const rel::Interface & A, const rel::Interface & B)
References diffSum(), EqualVersion, and rel::Interface::name().
bool operator>= (const rel::Interface & A, const rel::Interface & B)
References diffSum(), EqualVersion, and rel::Interface::name().
const ConfigVar& operator>> (const ConfigVar & , rel::Interface &)
References rel::Interface::age(), rel::Interface::current(), rel::Interface::name(), and rel::Interface::revision().