Youcrypt/EncFS: MACFileIO.cpp File Reference
MACFileIO.cpp File Reference
#include "MACFileIO.h"
#include "MemoryPool.h"
#include "FileUtils.h"
#include <rlog/rlog.h>
#include <rlog/Error.h>
#include <rlog/RLogChannel.h>
#include <cstring>
#include "i18n.h"
Functions
int dataBlockSize (const FSConfigPtr &cfg)
static off_t roundUpDivide (off_t numerator, int denominator)
static off_t locWithHeader (off_t offset, int blockSize, int headerSize)
static off_t locWithoutHeader (off_t offset, int blockSize, int headerSize)
Variables
static RLogChannel * Info = DEF_CHANNEL("info/MACFileIO", Log_Info)
static rel::Interface MACFileIO_iface ("FileIO/MAC", 2, 1, 0)
Function Documentation
int dataBlockSize (const FSConfigPtr & cfg)
static off_t locWithHeader (off_t offset, int blockSize, int headerSize) static
References roundUpDivide().
Referenced by MACFileIO::readOneBlock(), MACFileIO::truncate(), and MACFileIO::writeOneBlock().
static off_t locWithoutHeader (off_t offset, int blockSize, int headerSize) static
References roundUpDivide().
Referenced by MACFileIO::getAttr(), and MACFileIO::getSize().
static off_t roundUpDivide (off_t numerator, int denominator) inline static
Referenced by locWithHeader(), and locWithoutHeader().
Variable Documentation
RLogChannel* Info = DEF_CHANNEL("info/MACFileIO", Log_Info) static
Referenced by MACFileIO::MACFileIO().
rel::Interface MACFileIO_iface("FileIO/MAC", 2, 1, 0) static
Referenced by MACFileIO::interface().