Youcrypt/EncFS: NullCipher.cpp File Reference
NullCipher.cpp File Reference
#include "NullCipher.h"
#include "Range.h"
#include "Interface.h"
#include <boost/shared_ptr.hpp>
#include <rlog/rlog.h>
#include <cstring>
Classes
class NullKey
class NullDestructor
Functions
static shared_ptr< Cipher > NewNullCipher (const Interface &iface, int keyLen)
shared_ptr< AbstractCipherKey > gNullKey (new NullKey(), NullDestructor())
Variables
static Interface NullInterface ("nullCipher", 1, 0, 0)
static Range NullKeyRange (0)
static Range NullBlockRange (1, 4096, 1)
const bool HiddenCipher = true
static bool NullCipher_registered
Function Documentation
shared_ptr<AbstractCipherKey> gNullKey (new NullKey(), NullDestructor())
Referenced by NullCipher::newKey(), NullCipher::newRandomKey(), and NullCipher::readKey().
static shared_ptr<Cipher> NewNullCipher (const Interface & iface, int keyLen) static
Variable Documentation
const bool HiddenCipher = true
Range NullBlockRange(1, 4096, 1) static
bool NullCipher_registered static
Initial value:
 Cipher::Register("Null",
        "Non encrypting cipher.  For testing only!",
        NullInterface, NullKeyRange, NullBlockRange, NewNullCipher,
        HiddenCipher)
Interface NullInterface("nullCipher", 1, 0, 0) static
Range NullKeyRange(0) static