Youcrypt/EncFS: RawFileIO.cpp File Reference
RawFileIO.cpp File Reference
#include <unistd.h>
#include "RawFileIO.h"
#include <rlog/rlog.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <cstring>
#include <cerrno>
Functions
FileIO * NewRawFileIO (const rel::Interface &iface)
void swap (int &x, int &y)
static int open_readonly_workaround (const char *path, int flags)
Variables
static rel::Interface RawFileIO_iface ("FileIO/Raw", 1, 0, 0)
Function Documentation
FileIO* NewRawFileIO (const rel::Interface & iface)
static int open_readonly_workaround (const char * path, int flags) static
Referenced by RawFileIO::open().
void swap (int & x, int & y) inline
Referenced by RawFileIO::~RawFileIO().
Variable Documentation
rel::Interface RawFileIO_iface("FileIO/Raw", 1, 0, 0) static
Referenced by RawFileIO::interface().