Youcrypt/EncFS: SSL_Cipher.cpp File Reference
SSL_Cipher.cpp File Reference
#include "encfs.h"
#include "config.h"
#include <openssl/blowfish.h>
#include <openssl/sha.h>
#include <openssl/rand.h>
#include <openssl/err.h>
#include <openssl/hmac.h>
#include "SSL_Cipher.h"
#include "Range.h"
#include "MemoryPool.h"
#include "Mutex.h"
#include <cstring>
#include <ctime>
#include <sys/mman.h>
#include <sys/time.h>
#include <rlog/rlog.h>
#include <rlog/Error.h>
#include "i18n.h"
Classes
class SSLKey
Functions
int MIN (int a, int b)
int BytesToKey (int keyLen, int ivLen, const EVP_MD *md, const unsigned char *data, int dataLen, unsigned int rounds, unsigned char *key, unsigned char *iv)
long time_diff (const timeval &end, const timeval &start)
int TimedPBKDF2 (const char *pass, int passlen, const unsigned char *salt, int saltlen, int keylen, unsigned char *out, long desiredPDFTime)
unsigned char * KeyData (const shared_ptr< SSLKey > &key)
unsigned char * IVData (const shared_ptr< SSLKey > &key)
void initKey (const shared_ptr< SSLKey > &key, const EVP_CIPHER *_blockCipher, const EVP_CIPHER *_streamCipher, int _keySize)
static uint64_t _checksum_64 (SSLKey *key, const unsigned char *data, int dataLen, uint64_t *chainedIV)
static void flipBytes (unsigned char *buf, int size)
static void shuffleBytes (unsigned char *buf, int size)
static void unshuffleBytes (unsigned char *buf, int size)
Variables
const int MAX_KEYLENGTH = 32
const int MAX_IVLENGTH = 16
const int KEY_CHECKSUM_BYTES = 4
static Interface BlowfishInterface ("ssl/blowfish", 3, 0, 2)
static Interface AESInterface ("ssl/aes", 3, 0, 2)
static RLogChannel * CipherInfo = DEF_CHANNEL("info/cipher", Log_Info)
Function Documentation
static uint64_t _checksum_64 (SSLKey * key, const unsigned char * data, int dataLen, uint64_t * chainedIV) static
References SSLKey::mac_ctx, and SSLKey::mutex.
Referenced by SSL_Cipher::MAC_64().
int BytesToKey (int keyLen, int ivLen, const EVP_MD * md, const unsigned char * data, int dataLen, unsigned int rounds, unsigned char * key, unsigned char * iv)
References MIN.
Referenced by SSL_Cipher::newKey().
static void flipBytes (unsigned char * buf, int size) static
References MIN.
Referenced by SSL_Cipher::streamDecode(), and SSL_Cipher::streamEncode().
void initKey (const shared_ptr< SSLKey > & key, const EVP_CIPHER * _blockCipher, const EVP_CIPHER * _streamCipher, int _keySize)
References KeyData().
Referenced by SSL_Cipher::newKey(), SSL_Cipher::newRandomKey(), and SSL_Cipher::readKey().
unsigned char* IVData (const shared_ptr< SSLKey > & key) inline
Referenced by SSL_Cipher::newKey(), SSL_Cipher::setIVec(), and SSL_Cipher::setIVec_old().
unsigned char* KeyData (const shared_ptr< SSLKey > & key) inline
Referenced by initKey(), SSL_Cipher::newKey(), and SSL_Cipher::newRandomKey().
int MIN (int a, int b) inline
static void shuffleBytes (unsigned char * buf, int size) static
Referenced by SSL_Cipher::streamEncode().
long time_diff (const timeval & end, const timeval & start)
Referenced by TimedPBKDF2().
int TimedPBKDF2 (const char * pass, int passlen, const unsigned char * salt, int saltlen, int keylen, unsigned char * out, long desiredPDFTime)
References time_diff().
Referenced by SSL_Cipher::newKey().
static void unshuffleBytes (unsigned char * buf, int size) static
Referenced by SSL_Cipher::streamDecode().
Variable Documentation
Interface AESInterface("ssl/aes", 3, 0, 2) static
Interface BlowfishInterface("ssl/blowfish", 3, 0, 2) static
RLogChannel* CipherInfo = DEF_CHANNEL("info/cipher", Log_Info) static
Referenced by SSL_Cipher::SSL_Cipher().
const int KEY_CHECKSUM_BYTES = 4
Referenced by SSL_Cipher::encodedKeySize(), SSL_Cipher::readKey(), and SSL_Cipher::writeKey().
const int MAX_IVLENGTH = 16
Referenced by SSL_Cipher::blockDecode(), SSL_Cipher::blockEncode(), SSL_Cipher::readKey(), SSL_Cipher::streamDecode(), SSL_Cipher::streamEncode(), and SSL_Cipher::writeKey().
const int MAX_KEYLENGTH = 32
Referenced by SSL_Cipher::newRandomKey(), SSL_Cipher::readKey(), and SSL_Cipher::writeKey().