Youcrypt/EncFS: YoucryptFolder.cpp File Reference
YoucryptFolder.cpp File Reference
#include "YoucryptFolder.h"
#include "config.h"
#include "FSConfig.h"
#include "Cipher.h"
#include "NameIO.h"
#include "BlockNameIO.h"
#include "NullNameIO.h"
#include "YCNameIO.h"
#include "DirNode.h"
#include "Interface.h"
#include "autosprintf.h"
#include "i18n.h"
#include <rlog/rlog.h>
#include <rlog/Error.h>
#include <iostream>
#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>
Functions
static bool encryptFolder (shared_ptr< DirNode > root, const path &sourcePath, const string &destSuffix)
Cipher::CipherAlgorithm findCipherAlgorithm (const char *name, int keySize)
Function Documentation
static bool encryptFolder (shared_ptr< DirNode > root, const path & sourcePath, const string & destSuffix) static
Referenced by youcrypt::YoucryptFolder::importContent().
Cipher::CipherAlgorithm findCipherAlgorithm (const char * name, int keySize)
References Cipher::GetAlgorithmList().
Referenced by youcrypt::YoucryptFolder::createAtPath(), and createV6Config().