Youcrypt/EncFS: b/Interface.cpp File Reference
Interface.cpp File Reference
#include "Interface.h"
#include "ConfigVar.h"
#include <rlog/rlog.h>
#include <rlog/RLogChannel.h>
Functions
bool operator== (const Interface &A, const Interface &B)
bool operator!= (const Interface &A, const Interface &B)
static int sign (int a, int b)
static int diffSum (const Interface &A, const Interface &B)
bool operator< (const Interface &A, const Interface &B)
bool operator> (const Interface &A, const Interface &B)
bool operator<= (const Interface &A, const Interface &B)
bool operator>= (const Interface &A, const Interface &B)
ConfigVar & operator<< (ConfigVar &dst, const rel::Interface &iface)
const ConfigVar & operator>> (const ConfigVar &src, Interface &iface)
Variables
static RLogChannel * Info = DEF_CHANNEL("info/iface", Log_Info)
const int EqualVersion = (1 * 3 + 1) * 3 + 1
Function Documentation
static int diffSum (const Interface & A, const Interface & B) static
References rel::Interface::age(), rel::Interface::current(), rel::Interface::revision(), and sign().
Referenced by operator<(), operator<=(), operator>(), and operator>=().
bool operator!= (const Interface & A, const Interface & B)
bool operator< (const Interface & A, const Interface & B)
ConfigVar& operator<< (ConfigVar & dst, const rel::Interface & iface)
bool operator<= (const Interface & A, const Interface & B)
bool operator== (const Interface & A, const Interface & B)
bool operator> (const Interface & A, const Interface & B)
bool operator>= (const Interface & A, const Interface & B)
const ConfigVar& operator>> (const ConfigVar & src, Interface & iface)
static int sign (int a, int b) static
Referenced by diffSum().
Variable Documentation
const int EqualVersion = (1 * 3 + 1) * 3 + 1
Referenced by operator<(), operator<=(), operator>(), and operator>=().
RLogChannel* Info = DEF_CHANNEL("info/iface", Log_Info) static
Referenced by rel::Interface::implements().