Youcrypt/EncFS: base64.h File Reference
base64.h File Reference
Functions
int B64ToB256Bytes (int numB64Bytes)
int B256ToB64Bytes (int numB256Bytes)
void changeBase2 (unsigned char *src, int srcLength, int srcPow2, unsigned char *dst, int dstLength, int dstPow2)
void changeBase2Inline (unsigned char *buf, int srcLength, int srcPow2, int dst2Pow, bool outputPartialLastByte)
void B64ToAscii (unsigned char *buf, int length)
void AsciiToB64 (unsigned char *buf, int length)
void AsciiToB64 (unsigned char *out, const unsigned char *in, int length)
Function Documentation
void AsciiToB64 (unsigned char * buf, int length)
References AsciiToB64().
Referenced by AsciiToB64(), StreamNameIO::decodeName(), and BlockNameIO::decodeName().
void AsciiToB64 (unsigned char * out, const unsigned char * in, int length)
References Ascii2B64Table.
int B256ToB64Bytes (int numB256Bytes) inline
Referenced by Cipher::encodeAsString(), StreamNameIO::encodeName(), BlockNameIO::encodeName(), StreamNameIO::maxEncodedNameLen(), and BlockNameIO::maxEncodedNameLen().
void B64ToAscii (unsigned char * buf, int length)
References B642AsciiTable.
Referenced by Cipher::encodeAsString(), StreamNameIO::encodeName(), and BlockNameIO::encodeName().
int B64ToB256Bytes (int numB64Bytes) inline
Referenced by StreamNameIO::decodeName(), BlockNameIO::decodeName(), StreamNameIO::maxDecodedNameLen(), and BlockNameIO::maxDecodedNameLen().
void changeBase2 (unsigned char * src, int srcLength, int srcPow2, unsigned char * dst, int dstLength, int dstPow2)
Referenced by Cipher::encodeAsString().
void changeBase2Inline (unsigned char * buf, int srcLength, int srcPow2, int dst2Pow, bool outputPartialLastByte)
References changeBase2Inline().