Youcrypt/EncFS: base64.cpp File Reference
base64.cpp File Reference
#include "base64.h"
Functions
void changeBase2 (unsigned char *src, int srcLen, int src2Pow, unsigned char *dst, int dstLen, int dst2Pow)
static void changeBase2Inline (unsigned char *src, int srcLen, int src2Pow, int dst2Pow, bool outputPartialLastByte, unsigned long work, int workBits, unsigned char *outLoc)
void changeBase2Inline (unsigned char *src, int srcLen, int src2Pow, int dst2Pow, bool outputPartialLastByte)
void B64ToAscii (unsigned char *in, int length)
void AsciiToB64 (unsigned char *in, int length)
void AsciiToB64 (unsigned char *out, const unsigned char *in, int length)
Variables
static const char B642AsciiTable [] = ",-0123456789"
static const unsigned char Ascii2B64Table [] = " 01 23456789:; "
Function Documentation
void AsciiToB64 (unsigned char * in, int length)
References AsciiToB64().
Referenced by AsciiToB64(), StreamNameIO::decodeName(), and BlockNameIO::decodeName().
void AsciiToB64 (unsigned char * out, const unsigned char * in, int length)
References Ascii2B64Table.
void B64ToAscii (unsigned char * in, int length)
References B642AsciiTable.
Referenced by Cipher::encodeAsString(), StreamNameIO::encodeName(), and BlockNameIO::encodeName().
void changeBase2 (unsigned char * src, int srcLen, int src2Pow, unsigned char * dst, int dstLen, int dst2Pow)
Referenced by Cipher::encodeAsString().
static void changeBase2Inline (unsigned char * src, int srcLen, int src2Pow, int dst2Pow, bool outputPartialLastByte, unsigned long work, int workBits, unsigned char * outLoc) static
Referenced by changeBase2Inline(), StreamNameIO::decodeName(), BlockNameIO::decodeName(), StreamNameIO::encodeName(), and BlockNameIO::encodeName().
void changeBase2Inline (unsigned char * src, int srcLen, int src2Pow, int dst2Pow, bool outputPartialLastByte)
References changeBase2Inline().
Variable Documentation
const unsigned char Ascii2B64Table[] = " 01 23456789:; " static
Referenced by AsciiToB64().
const char B642AsciiTable[] = ",-0123456789" static
Referenced by B64ToAscii().