Youcrypt/EncFS: rel::Interface Class Reference
rel::Interface Class Reference
#include <Interface.h>
Public Member Functions
Interface (const char *name, int Current, int Revision, int Age)
Interface (const std::string &name, int Current, int Revision, int Age)
Interface (const Interface &src)
Interface ()
bool implements (const Interface &dst) const
const std::string & name () const
int current () const
int revision () const
int age () const
std::string & name ()
int & current ()
int & revision ()
int & age ()
Interface & operator= (const Interface &src)
Private Attributes
std::string _name
int _current
int _revision
int _age
Constructor & Destructor Documentation
Interface::Interface (const char * name, int Current, int Revision, int Age)
Version numbers as described by libtool: info://libtool/versioning Current - the most recent interface api that is implemented. Revision - the implementation number of the current interface. Age - the difference between the newest and oldest interfaces that are implemented.
Interface::Interface (const std::string & name, int Current, int Revision, int Age)
Interface::Interface (const Interface & src)
Interface::Interface ()
Member Function Documentation
int Interface::age () const
References _age.
Referenced by diffSum(), implements(), operator!=(), operator<<(), operator==(), operator>>(), and showFSInfo().
int & Interface::age ()
References _age.
int Interface::current () const
References _current.
Referenced by diffSum(), implements(), SSL_Cipher::newKey(), operator!=(), operator<<(), operator==(), operator>>(), boost::serialization::serialize(), SSL_Cipher::setIVec(), showFSInfo(), and SSL_Cipher::SSL_Cipher().
int & Interface::current ()
References _current.
bool Interface::implements (const Interface & dst) const
References age(), current(), Info, name(), and revision().
Referenced by runTests().
const std::string & Interface::name () const
References _name.
Referenced by implements(), operator!=(), operator<(), operator<<(), operator<=(), operator==(), operator>(), operator>=(), operator>>(), boost::serialization::serialize(), and SSL_Cipher::SSL_Cipher().
std::string & Interface::name ()
References _name.
Interface & Interface::operator= (const Interface & src)
References _age, _current, _name, and _revision.
int Interface::revision () const
References _revision.
Referenced by diffSum(), implements(), operator!=(), operator<<(), operator==(), operator>>(), boost::serialization::serialize(), and showFSInfo().
int & Interface::revision ()
References _revision.
Member Data Documentation
int rel::Interface::_age private
Referenced by age(), and operator=().
int rel::Interface::_current private
Referenced by current(), and operator=().
std::string rel::Interface::_name private
Referenced by name(), and operator=().
int rel::Interface::_revision private
Referenced by operator=(), and revision().
The documentation for this class was generated from the following files:
Interface.h
b/Interface.cpp
Interface.cpp