Youcrypt/EncFS: BlockNameIO Class Reference
BlockNameIO Class Reference
#include <BlockNameIO.h>
Public Member Functions
BlockNameIO (const rel::Interface &iface, const boost::shared_ptr< Cipher > &cipher, const CipherKey &key, int blockSize)
virtual ~BlockNameIO ()
virtual rel::Interface interface () const
virtual int maxEncodedNameLen (int plaintextNameLen) const
virtual int maxDecodedNameLen (int encodedNameLen) const
Public Member Functions inherited from NameIO
NameIO ()
virtual ~NameIO ()
void setChainedNameIV (bool enable)
bool getChainedNameIV () const
void setReverseEncryption (bool enable)
bool getReverseEncryption () const
std::string encodePath (const char *plaintextPath) const
std::string decodePath (const char *encodedPath) const
std::string encodePath (const char *plaintextPath, uint64_t *iv) const
std::string decodePath (const char *encodedPath, uint64_t *iv) const
std::string encodeName (const char *plaintextName, int length) const
std::string decodeName (const char *encodedName, int length) const
Static Public Member Functions
static rel::Interface CurrentInterface ()
static bool Enabled ()
Static Public Member Functions inherited from NameIO
static AlgorithmList GetAlgorithmList (bool includeHidden=false)
static shared_ptr< NameIO > New (const rel::Interface &iface, const shared_ptr< Cipher > &cipher, const CipherKey &key)
static shared_ptr< NameIO > New (const std::string &name, const shared_ptr< Cipher > &cipher, const CipherKey &key)
static bool Register (const char *name, const char *description, const rel::Interface &iface, Constructor constructor, bool hidden=false)
Protected Member Functions
virtual int encodeName (const char *plaintextName, int length, uint64_t *iv, char *encodedName) const
virtual int decodeName (const char *encodedName, int length, uint64_t *iv, char *plaintextName) const
Protected Member Functions inherited from NameIO
virtual int encodeName (const char *plaintextName, int length, char *encodedName) const
virtual int decodeName (const char *encodedName, int length, char *plaintextName) const
Private Attributes
int _interface
int _bs
boost::shared_ptr< Cipher > _cipher
CipherKey _key
Additional Inherited Members
Public Types inherited from NameIO
typedef shared_ptr< NameIO >(* Constructor)(const rel::Interface &iface, const shared_ptr< Cipher > &cipher, const CipherKey &key)
typedef std::list< Algorithm > AlgorithmList
Constructor & Destructor Documentation
BlockNameIO::BlockNameIO (const rel::Interface & iface, const boost::shared_ptr< Cipher > & cipher, const CipherKey & key, int blockSize)
BlockNameIO::~BlockNameIO () virtual
Member Function Documentation
Interface BlockNameIO::CurrentInterface () static
Referenced by youcrypt::YoucryptFolder::createAtPath(), createV6Config(), interface(), and runTests().
int BlockNameIO::decodeName (const char * encodedName, int length, uint64_t * iv, char * plaintextName) const protected virtual
Implements NameIO.
References _bs, _cipher, _interface, _key, AsciiToB64(), B64ToB256Bytes(), BUFFER_INIT, BUFFER_RESET, and changeBase2Inline().
bool BlockNameIO::Enabled () static
int BlockNameIO::encodeName (const char * plaintextName, int length, uint64_t * iv, char * encodedName) const protected virtual
Implements NameIO.
References _bs, _cipher, _interface, _key, B256ToB64Bytes(), B64ToAscii(), and changeBase2Inline().
Interface BlockNameIO::interface () const virtual
Implements NameIO.
References CurrentInterface().
int BlockNameIO::maxDecodedNameLen (int encodedNameLen) const virtual
Implements NameIO.
References B64ToB256Bytes().
int BlockNameIO::maxEncodedNameLen (int plaintextNameLen) const virtual
Implements NameIO.
References _bs, and B256ToB64Bytes().
Member Data Documentation
int BlockNameIO::_bs private
Referenced by decodeName(), encodeName(), and maxEncodedNameLen().
boost::shared_ptr<Cipher> BlockNameIO::_cipher private
Referenced by decodeName(), and encodeName().
int BlockNameIO::_interface private
Referenced by decodeName(), and encodeName().
CipherKey BlockNameIO::_key private
Referenced by decodeName(), and encodeName().
The documentation for this class was generated from the following files:
BlockNameIO.h
BlockNameIO.cpp