Youcrypt/EncFS: Range Class Reference
Range Class Reference
#include <Range.h>
Public Member Functions
Range ()
Range (int minMax)
Range (int min, int max, int increment)
bool allowed (int value) const
int closest (int value) const
int min () const
int max () const
int inc () const
Private Attributes
int minVal
int maxVal
int increment
Constructor & Destructor Documentation
Range::Range () inline
Range::Range (int minMax) inline
References increment, maxVal, and minVal.
Range::Range (int min, int max, int increment) inline
References increment, maxVal, and minVal.
Member Function Documentation
bool Range::allowed (int value) const inline
References increment, maxVal, and minVal.
Referenced by closest().
int Range::closest (int value) const inline
References allowed(), increment, maxVal, and minVal.
Referenced by selectBlockSize(), and selectKeySize().
int Range::inc () const inline
References increment.
Referenced by selectBlockSize(), and selectKeySize().
int Range::max () const inline
References maxVal.
Referenced by selectBlockSize(), and selectKeySize().
int Range::min () const inline
References minVal.
Referenced by selectBlockSize(), and selectKeySize().
Member Data Documentation
int Range::increment private
Referenced by allowed(), closest(), inc(), and Range().
int Range::maxVal private
Referenced by allowed(), closest(), max(), and Range().
int Range::minVal private
Referenced by allowed(), closest(), min(), and Range().
The documentation for this class was generated from the following file:
Range.h