Youcrypt/EncFS: FileNode Class Reference
FileNode Class Reference
#include <FileNode.h>
Public Member Functions
FileNode (DirNode *parent, const FSConfigPtr &cfg, const char *plaintextName, const char *cipherName)
~FileNode ()
const char * plaintextName () const
const char * cipherName () const
std::string plaintextParent () const
bool setName (const char *plaintextName, const char *cipherName, uint64_t iv, bool setIVFirst=true)
int mknod (mode_t mode, dev_t rdev, uid_t uid=0, gid_t gid=0)
int open (int flags) const
int getAttr (struct stat *stbuf) const
off_t getSize () const
ssize_t read (off_t offset, unsigned char *data, ssize_t size) const
bool write (off_t offset, unsigned char *data, ssize_t size)
int truncate (off_t size)
int sync (bool dataSync)
Private Member Functions
FileNode (const FileNode &src)
FileNode & operator= (const FileNode &src)
Private Attributes
pthread_mutex_t mutex
FSConfigPtr fsConfig
shared_ptr< FileIO > io
std::string _pname
std::string _cname
DirNode * parent
Constructor & Destructor Documentation
FileNode::FileNode (DirNode * parent, const FSConfigPtr & cfg, const char * plaintextName, const char * cipherName)
References _should_ignore().
FileNode::~FileNode ()
FileNode::FileNode (const FileNode & src) private
Member Function Documentation
const char * FileNode::cipherName () const
Referenced by _do_getattr().
int FileNode::getAttr (struct stat * stbuf) const
Referenced by _do_getattr().
off_t FileNode::getSize () const
int FileNode::mknod (mode_t mode, dev_t rdev, uid_t uid = 0, gid_t gid = 0)
References setfsgid(), and setfsuid().
int FileNode::open (int flags) const
Referenced by _do_flush().
FileNode& FileNode::operator= (const FileNode & src) private
const char * FileNode::plaintextName () const
string FileNode::plaintextParent () const
References parentDirectory().
ssize_t FileNode::read (off_t offset, unsigned char * data, ssize_t size) const
References IORequest::data, IORequest::dataLen, and IORequest::offset.
Referenced by _do_read().
bool FileNode::setName (const char * plaintextName, const char * cipherName, uint64_t iv, bool setIVFirst = true)
References setIV().
int FileNode::sync (bool dataSync)
Referenced by _do_fsync().
int FileNode::truncate (off_t size)
Referenced by _do_truncate().
bool FileNode::write (off_t offset, unsigned char * data, ssize_t size)
References IORequest::data, IORequest::dataLen, Info, and IORequest::offset.
Referenced by _do_write().
Member Data Documentation
std::string FileNode::_cname private
std::string FileNode::_pname private
FSConfigPtr FileNode::fsConfig private
shared_ptr<FileIO> FileNode::io private
pthread_mutex_t FileNode::mutex mutable private
DirNode* FileNode::parent private
The documentation for this class was generated from the following files:
FileNode.h
FileNode.cpp