Youcrypt/EncFS: FileIO Class Reference
FileIO Class Reference
#include <FileIO.h>
Public Member Functions
FileIO ()
virtual ~FileIO ()
virtual rel::Interface interface () const =0
virtual int blockSize () const
virtual void setFileName (const char *fileName)=0
virtual const char * getFileName () const =0
virtual bool setIV (uint64_t iv)
virtual int open (int flags)=0
virtual int getAttr (struct stat *stbuf) const =0
virtual off_t getSize () const =0
virtual ssize_t read (const IORequest &req) const =0
virtual bool write (const IORequest &req)=0
virtual int truncate (off_t size)=0
virtual bool isWritable () const =0
Private Member Functions
FileIO (const FileIO &)
FileIO & operator= (const FileIO &)
Constructor & Destructor Documentation
FileIO::FileIO ()
FileIO::~FileIO () virtual
FileIO::FileIO (const FileIO &) private
Member Function Documentation
int FileIO::blockSize () const virtual
Reimplemented in BlockFileIO.
virtual int FileIO::getAttr (struct stat * stbuf) const pure virtual
Implemented in CipherFileIO, MACFileIO, and RawFileIO.
virtual const char* FileIO::getFileName () const pure virtual
Implemented in CipherFileIO, MACFileIO, and RawFileIO.
virtual off_t FileIO::getSize () const pure virtual
Implemented in CipherFileIO, MACFileIO, and RawFileIO.
Referenced by BlockFileIO::truncate(), and BlockFileIO::write().
virtual rel::Interface FileIO::interface () const pure virtual
Implemented in CipherFileIO, MACFileIO, and RawFileIO.
virtual bool FileIO::isWritable () const pure virtual
Implemented in CipherFileIO, MACFileIO, and RawFileIO.
virtual int FileIO::open (int flags) pure virtual
Implemented in CipherFileIO, MACFileIO, and RawFileIO.
FileIO& FileIO::operator= (const FileIO &) private
virtual ssize_t FileIO::read (const IORequest & req) const pure virtual
Implemented in RawFileIO, and BlockFileIO.
virtual void FileIO::setFileName (const char * fileName) pure virtual
Implemented in CipherFileIO, MACFileIO, and RawFileIO.
bool FileIO::setIV (uint64_t iv) virtual
Reimplemented in CipherFileIO, and MACFileIO.
virtual int FileIO::truncate (off_t size) pure virtual
Implemented in CipherFileIO, MACFileIO, and RawFileIO.
Referenced by BlockFileIO::truncate().
virtual bool FileIO::write (const IORequest & req) pure virtual
Implemented in RawFileIO, and BlockFileIO.
The documentation for this class was generated from the following files:
FileIO.h
FileIO.cpp