Youcrypt/EncFS: MACFileIO Class Reference
MACFileIO Class Reference
#include <MACFileIO.h>
Public Member Functions
MACFileIO (const shared_ptr< FileIO > &base, const FSConfigPtr &cfg)
MACFileIO ()
virtual ~MACFileIO ()
virtual rel::Interface interface () const
virtual void setFileName (const char *fileName)
virtual const char * getFileName () const
virtual bool setIV (uint64_t iv)
virtual int open (int flags)
virtual int getAttr (struct stat *stbuf) const
virtual off_t getSize () const
virtual int truncate (off_t size)
virtual bool isWritable () const
Public Member Functions inherited from BlockFileIO
BlockFileIO (int blockSize, const FSConfigPtr &cfg)
virtual ~BlockFileIO ()
virtual ssize_t read (const IORequest &req) const
virtual bool write (const IORequest &req)
virtual int blockSize () const
Public Member Functions inherited from FileIO
FileIO ()
virtual ~FileIO ()
Private Member Functions
virtual ssize_t readOneBlock (const IORequest &req) const
virtual bool writeOneBlock (const IORequest &req)
Private Attributes
shared_ptr< FileIO > base
shared_ptr< Cipher > cipher
CipherKey key
int macBytes
int randBytes
bool warnOnly
Additional Inherited Members
Protected Member Functions inherited from BlockFileIO
int truncate (off_t size, FileIO *base)
void padFile (off_t oldSize, off_t newSize, bool forceWrite)
ssize_t cacheReadOneBlock (const IORequest &req) const
bool cacheWriteOneBlock (const IORequest &req)
Protected Attributes inherited from BlockFileIO
int _blockSize
bool _allowHoles
IORequest _cache
Constructor & Destructor Documentation
MACFileIO::MACFileIO (const shared_ptr< FileIO > & base, const FSConfigPtr & cfg)
References Info, macBytes, and randBytes.
MACFileIO::MACFileIO ()
MACFileIO::~MACFileIO () virtual
Member Function Documentation
int MACFileIO::getAttr (struct stat * stbuf) const virtual
Implements FileIO.
References base, BlockFileIO::blockSize(), locWithoutHeader(), macBytes, and randBytes.
const char * MACFileIO::getFileName () const virtual
Implements FileIO.
References base.
off_t MACFileIO::getSize () const virtual
Implements FileIO.
References base, BlockFileIO::blockSize(), locWithoutHeader(), macBytes, and randBytes.
rel::Interface MACFileIO::interface () const virtual
Implements FileIO.
References MACFileIO_iface.
bool MACFileIO::isWritable () const virtual
Implements FileIO.
References base.
int MACFileIO::open (int flags) virtual
Implements FileIO.
References base.
ssize_t MACFileIO::readOneBlock (const IORequest & req) const private virtual
Implements BlockFileIO.
References _, BlockFileIO::_allowHoles, MemoryPool::allocate(), base, BlockFileIO::blockSize(), cipher, MemBlock::data, IORequest::data, IORequest::dataLen, key, locWithHeader(), macBytes, IORequest::offset, randBytes, MemoryPool::release(), and warnOnly.
void MACFileIO::setFileName (const char * fileName) virtual
Implements FileIO.
References base.
bool MACFileIO::setIV (uint64_t iv) virtual
Reimplemented from FileIO.
References base.
int MACFileIO::truncate (off_t size) virtual
Implements FileIO.
References base, BlockFileIO::blockSize(), locWithHeader(), macBytes, and randBytes.
bool MACFileIO::writeOneBlock (const IORequest & req) private virtual
Implements BlockFileIO.
References MemoryPool::allocate(), base, BlockFileIO::blockSize(), cipher, MemBlock::data, IORequest::data, IORequest::dataLen, key, locWithHeader(), macBytes, IORequest::offset, randBytes, and MemoryPool::release().
Member Data Documentation
shared_ptr<FileIO> MACFileIO::base private
Referenced by getAttr(), getFileName(), getSize(), isWritable(), open(), readOneBlock(), setFileName(), setIV(), truncate(), and writeOneBlock().
shared_ptr<Cipher> MACFileIO::cipher private
Referenced by readOneBlock(), and writeOneBlock().
CipherKey MACFileIO::key private
Referenced by readOneBlock(), and writeOneBlock().
int MACFileIO::macBytes private
Referenced by getAttr(), getSize(), MACFileIO(), readOneBlock(), truncate(), and writeOneBlock().
int MACFileIO::randBytes private
Referenced by getAttr(), getSize(), MACFileIO(), readOneBlock(), truncate(), and writeOneBlock().
bool MACFileIO::warnOnly private
Referenced by readOneBlock().
The documentation for this class was generated from the following files:
MACFileIO.h
MACFileIO.cpp