Youcrypt/EncFS: DirTraverse Class Reference
DirTraverse Class Reference
#include <DirNode.h>
Public Member Functions
DirTraverse (const shared_ptr< DIR > &dirPtr, uint64_t iv, const shared_ptr< NameIO > &naming)
DirTraverse (const DirTraverse &src)
~DirTraverse ()
DirTraverse & operator= (const DirTraverse &src)
bool valid () const
std::string nextPlaintextName (int *fileType=0, ino_t *inode=0)
std::string nextInvalid ()
Private Attributes
shared_ptr< DIR > dir
uint64_t iv
shared_ptr< NameIO > naming
Constructor & Destructor Documentation
DirTraverse::DirTraverse (const shared_ptr< DIR > & dirPtr, uint64_t iv, const shared_ptr< NameIO > & naming)
DirTraverse::DirTraverse (const DirTraverse & src)
DirTraverse::~DirTraverse ()
References dir, iv, and naming.
Member Function Documentation
std::string DirTraverse::nextInvalid ()
References _nextName(), dir, iv, and naming.
Referenced by showcruft().
std::string DirTraverse::nextPlaintextName (int * fileType = 0, ino_t * inode = 0)
References _nextName(), dir, iv, and naming.
Referenced by cmd_ls(), encfs_getdir(), showcruft(), and traverseDirs().
DirTraverse & DirTraverse::operator= (const DirTraverse & src)
References dir, iv, and naming.
bool DirTraverse::valid () const inline
References dir.
Referenced by cmd_ls(), encfs_getdir(), showcruft(), and traverseDirs().
Member Data Documentation
shared_ptr<DIR> DirTraverse::dir private
Referenced by nextInvalid(), nextPlaintextName(), operator=(), valid(), and ~DirTraverse().
uint64_t DirTraverse::iv private
Referenced by nextInvalid(), nextPlaintextName(), operator=(), and ~DirTraverse().
shared_ptr<NameIO> DirTraverse::naming private
Referenced by nextInvalid(), nextPlaintextName(), operator=(), and ~DirTraverse().
The documentation for this class was generated from the following files:
DirNode.h
DirNode.cpp