Youcrypt/EncFS: youcrypt::YoucryptFolder Class Reference
youcrypt::YoucryptFolder Class Reference
#include <YoucryptFolder.h>
Public Types
enum Status {
statusUnknown, uninitialized, configError, initialized,
processing, mounted
}
Helper opts initialization function.
Public Member Functions
YoucryptFolder (const path &, const YoucryptFolderOpts &, const Credentials &)
Create a new object representing encrypted content at path.
bool createAtPath (const path &, const YoucryptFolderOpts &, const Credentials &)
Create a new config. at path and loads it up.
bool loadConfigAtPath (const path &, const Credentials &)
Load config at path.
bool importContent (const path &)
Import content at the path specified into the folder.
bool importContent (const path &, const string &)
Import content at the path specified into the dest (suffix).
bool exportContent (const path &, const path &)
Same as import, except not!
bool addCredential (const Credentials &)
Add another cred. to an initialized folder.
Private Attributes
EncFS_Context ctx
boost::shared_ptr< Cipher > cipher
CipherKey volumeKey
boost::shared_ptr< DirNode > rootNode
path mountPoint
Status status
bool idleTracking
FIXME: Not yet implemented. Need to do this.
Member Enumeration Documentation
enum youcrypt::YoucryptFolder::Status
Helper opts initialization function.
Enumerator:
statusUnknown
Status is not known (not parseable, not readable, etc.)
uninitialized
Directory exists but is not a Youcrypt folder. (no config files, etc.)
configError
Directory contains a (partially) corrupt config.
initialized
Directory is a proper Youcrypt folder.
processing
Directory is being processed. (files are being added / deleted, key is being changed, etc.)
mounted
Directory is initialized at mounted.
Constructor & Destructor Documentation
YoucryptFolder::YoucryptFolder (const path & _rootPath, const YoucryptFolderOpts & _opts, const Credentials & creds)
Create a new object representing encrypted content at path.
Implementation: Try to loadConfig and createAtPath otherwise.
References createAtPath(), and loadConfigAtPath().
Member Function Documentation
bool YoucryptFolder::addCredential (const Credentials & newCred)
Add another cred. to an initialized folder.
References cipher, Config_YC, configError, initialized, mounted, mountPoint, processing, readConfig(), saveConfig(), status, and volumeKey.
bool YoucryptFolder::createAtPath (const path & _rootPath, const YoucryptFolderOpts & opts, const Credentials & cred)
Create a new config. at path and loads it up.
Implementation: must be very similar to CreateV6Config (except for Youcrypt specific customizations).
References youcrypt::YoucryptFolderOpts::blockMACBytes, youcrypt::YoucryptFolderOpts::blockMACRandBytes, youcrypt::YoucryptFolderOpts::blockSize, youcrypt::YoucryptFolderOpts::chainedIV, cipher, Config_YC, ctx, YCNameIO::CurrentInterface(), NullNameIO::CurrentInterface(), BlockNameIO::CurrentInterface(), youcrypt::YoucryptFolderOpts::externalIV, youcrypt::YoucryptFolderOpts::filenameEncrypt, youcrypt::YoucryptFolderOpts::filenameEncryption, youcrypt::YoucryptFolderOpts::filenamePlain, youcrypt::YoucryptFolderOpts::filenameYC, findCipherAlgorithm(), youcrypt::YoucryptFolderOpts::idleTracking, youcrypt::YoucryptFolderOpts::ignoreList, initialized, youcrypt::YoucryptFolderOpts::keySize, mountPoint, Cipher::CipherAlgorithm::name, NameIO::New(), Cipher::New(), EncFS_Context::opts, EncFS_Context::publicFilesystem, rootNode, saveConfig(), EncFS_Context::setRoot(), status, statusUnknown, youcrypt::YoucryptFolderOpts::uniqueIV, and volumeKey.
Referenced by YoucryptFolder().
bool YoucryptFolder::exportContent (const path & , const path &)
Same as import, except not!
bool YoucryptFolder::importContent (const path & p)
Import content at the path specified into the folder.
(<blah> goes to /<blah> in the folder).
Referenced by main().
bool YoucryptFolder::importContent (const path & sourcePath, const string & destSuffix)
Import content at the path specified into the dest (suffix).
Import path into relative path specified by the second argument.
References encryptFolder(), and rootNode.
bool YoucryptFolder::loadConfigAtPath (const path & _rootPath, const Credentials & cred)
Load config at path.
Implementation: must be very simialr to createV6Config (except for Youcrypt specific customizations). Details of Youcrypt modification (from encfs/initFS()):
reverseEncryption is not used.
cred is passed the cipher and the encrypted volumeKey, to decode the volume key.
forceDecode is always set.
References cipher, Config_None, configError, initialized, mountPoint, NameIO::New(), readConfig(), rootNode, status, statusUnknown, and volumeKey.
Referenced by YoucryptFolder().
Member Data Documentation
boost::shared_ptr<Cipher> youcrypt::YoucryptFolder::cipher private
Referenced by addCredential(), createAtPath(), and loadConfigAtPath().
EncFS_Context youcrypt::YoucryptFolder::ctx private
Referenced by createAtPath().
bool youcrypt::YoucryptFolder::idleTracking private
FIXME: Not yet implemented. Need to do this.
path youcrypt::YoucryptFolder::mountPoint private
Referenced by addCredential(), createAtPath(), and loadConfigAtPath().
boost::shared_ptr<DirNode> youcrypt::YoucryptFolder::rootNode private
Referenced by createAtPath(), importContent(), and loadConfigAtPath().
Status youcrypt::YoucryptFolder::status private
Referenced by addCredential(), createAtPath(), and loadConfigAtPath().
CipherKey youcrypt::YoucryptFolder::volumeKey private
Referenced by addCredential(), createAtPath(), and loadConfigAtPath().
The documentation for this class was generated from the following files:
YoucryptFolder.h
YoucryptFolder.cpp