Youcrypt/EncFS: EncFS_Context Class Reference
EncFS_Context Class Reference
#include <Context.h>
Classes
struct Placeholder
Public Member Functions
EncFS_Context ()
~EncFS_Context ()
shared_ptr< FileNode > getNode (void *ptr)
shared_ptr< FileNode > lookupNode (const char *path)
int getAndResetUsageCounter ()
int openFileCount () const
void * putNode (const char *path, const shared_ptr< FileNode > &node)
void eraseNode (const char *path, void *placeholder)
void renameNode (const char *oldName, const char *newName)
void setRoot (const shared_ptr< DirNode > &root)
shared_ptr< DirNode > getRoot (int *err)
bool isMounted ()
EncFS_Context ()
~EncFS_Context ()
shared_ptr< FileNode > getNode (void *ptr)
shared_ptr< FileNode > lookupNode (const char *path)
int getAndResetUsageCounter ()
int openFileCount () const
void * putNode (const char *path, const shared_ptr< FileNode > &node)
void eraseNode (const char *path, void *placeholder)
void renameNode (const char *oldName, const char *newName)
void setRoot (const shared_ptr< DirNode > &root)
shared_ptr< DirNode > getRoot (int *err)
bool isMounted ()
Public Attributes
shared_ptr< EncFS_Args > args
shared_ptr< EncFS_Opts > opts
bool publicFilesystem
std::string rootCipherDir
bool running
pthread_t monitorThread
pthread_cond_t wakeupCond
pthread_mutex_t wakeupMutex
Private Types
typedef std::map< std::string,
std::set< Placeholder * > > FileMap
typedef std::map< std::string,
std::set< Placeholder * > > FileMap
Private Attributes
pthread_mutex_t contextMutex
FileMap openFiles
int usageCount
shared_ptr< DirNode > root
Member Typedef Documentation
typedef std::map< std::string, std::set<Placeholder*> > EncFS_Context::FileMap private
typedef std::map< std::string, std::set<Placeholder*> > EncFS_Context::FileMap private
Constructor & Destructor Documentation
EncFS_Context::EncFS_Context ()
EncFS_Context::~EncFS_Context ()
EncFS_Context::EncFS_Context ()
EncFS_Context::~EncFS_Context ()
Member Function Documentation
void EncFS_Context::eraseNode (const char * path, void * placeholder)
Referenced by encfs_release().
void EncFS_Context::eraseNode (const char * path, void * placeholder)
int EncFS_Context::getAndResetUsageCounter ()
Referenced by idleMonitor().
int EncFS_Context::getAndResetUsageCounter ()
shared_ptr<FileNode> EncFS_Context::getNode (void * ptr)
shared_ptr< FileNode > EncFS_Context::getNode (void * ptr)
References EncFS_Context::Placeholder::node.
shared_ptr<DirNode> EncFS_Context::getRoot (int * err)
shared_ptr< DirNode > EncFS_Context::getRoot (int * err)
References remountFS().
Referenced by _do_getattr(), _do_readlink(), encfs_getdir(), encfs_link(), encfs_mkdir(), encfs_mknod(), encfs_open(), encfs_rename(), encfs_symlink(), encfs_unlink(), withCipherPath(), and withFileNode().
bool EncFS_Context::isMounted ()
bool EncFS_Context::isMounted ()
Referenced by idleMonitor().
shared_ptr< FileNode > EncFS_Context::lookupNode (const char * path)
Referenced by DirNode::findOrCreate(), and DirNode::unlink().
shared_ptr<FileNode> EncFS_Context::lookupNode (const char * path)
int EncFS_Context::openFileCount () const
Referenced by idleMonitor().
int EncFS_Context::openFileCount () const
void* EncFS_Context::putNode (const char * path, const shared_ptr< FileNode > & node)
void* EncFS_Context::putNode (const char * path, const shared_ptr< FileNode > & node)
Referenced by encfs_open().
void EncFS_Context::renameNode (const char * oldName, const char * newName)
Referenced by DirNode::renameNode().
void EncFS_Context::renameNode (const char * oldName, const char * newName)
void EncFS_Context::setRoot (const shared_ptr< DirNode > & root)
Referenced by youcrypt::YoucryptFolder::createAtPath(), main(), remountFS(), and unmountFS().
void EncFS_Context::setRoot (const shared_ptr< DirNode > & root)
Member Data Documentation
shared_ptr< EncFS_Args > EncFS_Context::args
Referenced by encfs_destroy(), encfs_init(), idleMonitor(), main(), and unmountFS().
pthread_mutex_t EncFS_Context::contextMutex mutable private
pthread_t EncFS_Context::monitorThread
Referenced by encfs_destroy(), and encfs_init().
FileMap EncFS_Context::openFiles private
shared_ptr< EncFS_Opts > EncFS_Context::opts
Referenced by youcrypt::YoucryptFolder::createAtPath(), main(), and remountFS().
bool EncFS_Context::publicFilesystem
Referenced by youcrypt::YoucryptFolder::createAtPath(), encfs_mkdir(), encfs_mknod(), encfs_symlink(), and main().
shared_ptr< DirNode > EncFS_Context::root private
std::string EncFS_Context::rootCipherDir
Referenced by encfs_statfs().
bool EncFS_Context::running
Referenced by encfs_destroy(), encfs_init(), and idleMonitor().
int EncFS_Context::usageCount private
pthread_cond_t EncFS_Context::wakeupCond
Referenced by encfs_destroy(), and idleMonitor().
pthread_mutex_t EncFS_Context::wakeupMutex
Referenced by encfs_destroy(), and idleMonitor().
The documentation for this class was generated from the following files:
b/Context.h
Context.h
Context.cpp