Youcrypt/EncFS: DirNode Class Reference
DirNode Class Reference
#include <DirNode.h>
Public Member Functions
DirNode (EncFS_Context *ctx, const std::string &sourceDir, const FSConfigPtr &config)
~DirNode ()
std::string rootDirectory ()
shared_ptr< FileNode > lookupNode (const char *plaintextName, const char *requestor)
shared_ptr< FileNode > openNode (const char *plaintextName, const char *requestor, int flags, int *openResult)
shared_ptr< FileNode > directLookup (const char *realPath)
std::string cipherPath (const char *plaintextPath)
std::string cipherPathWithoutRoot (const char *plaintextPath)
std::string plainPath (const char *cipherPath)
std::string relativeCipherPath (const char *plaintextPath)
bool hasDirectoryNameDependency () const
int unlink (const char *plaintextName)
DirTraverse openDir (const char *plainDirName)
int mkdir (const char *plaintextPath, mode_t mode, uid_t uid=0, gid_t gid=0)
int rename (const char *fromPlaintext, const char *toPlaintext)
int link (const char *from, const char *to)
int idleSeconds ()
Protected Member Functions
shared_ptr< FileNode > renameNode (const char *from, const char *to)
shared_ptr< FileNode > renameNode (const char *from, const char *to, bool forwardMode)
shared_ptr< RenameOp > newRenameOp (const char *from, const char *to)
Private Member Functions
bool genRenameList (std::list< RenameEl > &list, const char *fromP, const char *toP)
shared_ptr< FileNode > findOrCreate (const char *plainName)
Private Attributes
pthread_mutex_t mutex
EncFS_Context * ctx
std::string rootDir
FSConfigPtr fsConfig
shared_ptr< NameIO > naming
Friends
class RenameOp
Constructor & Destructor Documentation
DirNode::DirNode (EncFS_Context * ctx, const std::string & sourceDir, const FSConfigPtr & config)
References ctx, fsConfig, mutex, naming, and rootDir.
DirNode::~DirNode ()
Member Function Documentation
string DirNode::cipherPath (const char * plaintextPath)
References naming, and rootDir.
string DirNode::cipherPathWithoutRoot (const char * plaintextPath)
References naming.
shared_ptr< FileNode > DirNode::directLookup (const char * realPath)
References fsConfig.
shared_ptr< FileNode > DirNode::findOrCreate (const char * plainName) private
References ctx, fsConfig, Info, EncFS_Context::lookupNode(), naming, and rootDir.
Referenced by lookupNode(), openNode(), rename(), and renameNode().
bool DirNode::genRenameList (std::list< RenameEl > & list, const char * fromP, const char * toP) private
References RenameEl::isDirectory, isDirectory(), naming, RenameEl::newCName, RenameEl::newPName, RenameEl::oldCName, RenameEl::oldPName, and rootDir.
Referenced by newRenameOp().
bool DirNode::hasDirectoryNameDependency () const
References naming.
Referenced by rename().
int DirNode::idleSeconds ()
int DirNode::link (const char * from, const char * to)
References fsConfig, Info, mutex, naming, and rootDir.
shared_ptr< FileNode > DirNode::lookupNode (const char * plaintextName, const char * requestor)
References findOrCreate(), and mutex.
int DirNode::mkdir (const char * plaintextPath, mode_t mode, uid_t uid = 0, gid_t gid = 0)
References Info, naming, rootDir, setfsgid(), and setfsuid().
shared_ptr< RenameOp > DirNode::newRenameOp (const char * from, const char * to) protected
References genRenameList(), and RenameOp.
Referenced by rename().
DirTraverse DirNode::openDir (const char * plainDirName)
References naming, and rootDir.
shared_ptr< FileNode > DirNode::openNode (const char * plaintextName, const char * requestor, int flags, int * openResult)
References findOrCreate(), and mutex.
string DirNode::plainPath (const char * cipherPath)
References naming, and rootDir.
Referenced by testNameCoding().
string DirNode::relativeCipherPath (const char * plaintextPath)
References naming.
Referenced by testNameCoding().
int DirNode::rename (const char * fromPlaintext, const char * toPlaintext)
References findOrCreate(), hasDirectoryNameDependency(), Info, isDirectory(), mutex, naming, newRenameOp(), renameNode(), and rootDir.
shared_ptr< FileNode > DirNode::renameNode (const char * from, const char * to) protected
Referenced by RenameOp::apply(), rename(), and RenameOp::undo().
shared_ptr< FileNode > DirNode::renameNode (const char * from, const char * to, bool forwardMode) protected
References ctx, findOrCreate(), Info, naming, EncFS_Context::renameNode(), and rootDir.
string DirNode::rootDirectory ()
References rootDir.
int DirNode::unlink (const char * plaintextName)
References ctx, Info, EncFS_Context::lookupNode(), mutex, naming, and rootDir.
Friends And Related Function Documentation
friend class RenameOp friend
Referenced by newRenameOp().
Member Data Documentation
EncFS_Context* DirNode::ctx private
Referenced by DirNode(), findOrCreate(), renameNode(), and unlink().
FSConfigPtr DirNode::fsConfig private
Referenced by directLookup(), DirNode(), findOrCreate(), and link().
pthread_mutex_t DirNode::mutex private
Referenced by DirNode(), link(), lookupNode(), openNode(), rename(), and unlink().
shared_ptr<NameIO> DirNode::naming private
Referenced by cipherPath(), cipherPathWithoutRoot(), DirNode(), findOrCreate(), genRenameList(), hasDirectoryNameDependency(), link(), mkdir(), openDir(), plainPath(), relativeCipherPath(), rename(), renameNode(), and unlink().
std::string DirNode::rootDir private
Referenced by cipherPath(), DirNode(), findOrCreate(), genRenameList(), link(), mkdir(), openDir(), plainPath(), rename(), renameNode(), rootDirectory(), and unlink().
The documentation for this class was generated from the following files:
DirNode.h
DirNode.cpp