Youcrypt/EncFS: NullCipher Class Reference
NullCipher Class Reference
#include <NullCipher.h>
Public Member Functions
NullCipher (const rel::Interface &iface)
virtual ~NullCipher ()
virtual rel::Interface interface () const
virtual CipherKey newKey (const char *password, int passwdLength, int &iterationCount, long desiredDuration, const unsigned char *salt, int saltLen)
virtual CipherKey newKey (const char *password, int passwdLength)
virtual CipherKey newRandomKey ()
virtual CipherKey readKey (const unsigned char *data, const CipherKey &encodingKey, bool checkKey)
virtual void writeKey (const CipherKey &key, unsigned char *data, const CipherKey &encodingKey)
virtual bool compareKey (const CipherKey &A, const CipherKey &B) const
virtual int keySize () const
virtual int encodedKeySize () const
virtual int cipherBlockSize () const
virtual bool randomize (unsigned char *buf, int len, bool strongRandom) const
virtual uint64_t MAC_64 (const unsigned char *data, int len, const CipherKey &key, uint64_t *chainedIV) const
virtual bool streamEncode (unsigned char *in, int len, uint64_t iv64, const CipherKey &key) const
virtual bool streamDecode (unsigned char *in, int len, uint64_t iv64, const CipherKey &key) const
virtual bool blockEncode (unsigned char *buf, int size, uint64_t iv64, const CipherKey &key) const
virtual bool blockDecode (unsigned char *buf, int size, uint64_t iv64, const CipherKey &key) const
Public Member Functions inherited from Cipher
Cipher ()
virtual ~Cipher ()
virtual std::string encodeAsString (const CipherKey &key, const CipherKey &encodingKey)
unsigned int MAC_32 (const unsigned char *src, int len, const CipherKey &key, uint64_t *chainedIV=0) const
unsigned int MAC_16 (const unsigned char *src, int len, const CipherKey &key, uint64_t *chainedIV=0) const
virtual bool nameEncode (unsigned char *data, int len, uint64_t iv64, const CipherKey &key) const
virtual bool nameDecode (unsigned char *data, int len, uint64_t iv64, const CipherKey &key) const
Static Public Member Functions
static bool Enabled ()
Static Public Member Functions inherited from Cipher
static AlgorithmList GetAlgorithmList (bool includeHidden=false)
static boost::shared_ptr< Cipher > New (const rel::Interface &iface, int keyLen=-1)
static boost::shared_ptr< Cipher > New (const std::string &cipherName, int keyLen=-1)
static bool Register (const char *cipherName, const char *description, const rel::Interface &iface, CipherConstructor constructor, bool hidden=false)
static bool Register (const char *cipherName, const char *description, const rel::Interface &iface, const Range &keyLength, const Range &blockSize, CipherConstructor constructor, bool hidden=false)
Private Attributes
rel::Interface iface
Additional Inherited Members
Public Types inherited from Cipher
typedef boost::shared_ptr
< Cipher >(* CipherConstructor)(const rel::Interface &iface, int keyLenBits)
typedef std::list
< CipherAlgorithm > AlgorithmList
Constructor & Destructor Documentation
NullCipher::NullCipher (const rel::Interface & iface)
NullCipher::~NullCipher () virtual
Member Function Documentation
bool NullCipher::blockDecode (unsigned char * buf, int size, uint64_t iv64, const CipherKey & key) const virtual
Implements Cipher.
bool NullCipher::blockEncode (unsigned char * buf, int size, uint64_t iv64, const CipherKey & key) const virtual
Implements Cipher.
int NullCipher::cipherBlockSize () const virtual
Implements Cipher.
bool NullCipher::compareKey (const CipherKey & A, const CipherKey & B) const virtual
Implements Cipher.
bool NullCipher::Enabled () static
int NullCipher::encodedKeySize () const virtual
Implements Cipher.
Interface NullCipher::interface () const virtual
Implements Cipher.
int NullCipher::keySize () const virtual
Implements Cipher.
uint64_t NullCipher::MAC_64 (const unsigned char * data, int len, const CipherKey & key, uint64_t * chainedIV) const virtual
Implements Cipher.
CipherKey NullCipher::newKey (const char * password, int passwdLength, int & iterationCount, long desiredDuration, const unsigned char * salt, int saltLen) virtual
Implements Cipher.
References gNullKey().
CipherKey NullCipher::newKey (const char * password, int passwdLength) virtual
Implements Cipher.
References gNullKey().
CipherKey NullCipher::newRandomKey () virtual
Implements Cipher.
References gNullKey().
bool NullCipher::randomize (unsigned char * buf, int len, bool strongRandom) const virtual
Implements Cipher.
CipherKey NullCipher::readKey (const unsigned char * data, const CipherKey & encodingKey, bool checkKey) virtual
Implements Cipher.
References gNullKey().
bool NullCipher::streamDecode (unsigned char * in, int len, uint64_t iv64, const CipherKey & key) const virtual
Implements Cipher.
bool NullCipher::streamEncode (unsigned char * in, int len, uint64_t iv64, const CipherKey & key) const virtual
Implements Cipher.
void NullCipher::writeKey (const CipherKey & key, unsigned char * data, const CipherKey & encodingKey) virtual
Implements Cipher.
Member Data Documentation
rel::Interface NullCipher::iface private
The documentation for this class was generated from the following files:
NullCipher.h
NullCipher.cpp