Youcrypt/EncFS: ConfigReader Class Reference
ConfigReader Class Reference
#include <ConfigReader.h>
Public Member Functions
ConfigReader ()
~ConfigReader ()
bool load (const char *fileName)
bool save (const char *fileName) const
ConfigVar toVar () const
bool loadFromVar (ConfigVar &var)
ConfigVar operator[] (const std::string &varName) const
ConfigVar & operator[] (const std::string &varName)
Private Attributes
std::map< std::string, ConfigVar > vars
Constructor & Destructor Documentation
ConfigReader::ConfigReader ()
ConfigReader::~ConfigReader ()
Member Function Documentation
bool ConfigReader::load (const char * fileName)
References ConfigVar::write().
Referenced by readV4Config(), and readV5Config().
bool ConfigReader::loadFromVar (ConfigVar & var)
References ConfigVar::readInt(), and ConfigVar::resetOffset().
ConfigVar ConfigReader::operator[] (const std::string & varName) const
ConfigVar & ConfigReader::operator[] (const std::string & varName)
bool ConfigReader::save (const char * fileName) const
References ConfigVar::buffer(), and ConfigVar::size().
Referenced by writeV4Config(), and writeV5Config().
ConfigVar ConfigReader::toVar () const
References ConfigVar::write(), and ConfigVar::writeInt().
Member Data Documentation
std::map<std::string, ConfigVar> ConfigReader::vars private
The documentation for this class was generated from the following files:
ConfigReader.h
ConfigReader.cpp