Youcrypt/EncFS: NameIO Class Reference
NameIO Class Reference
#include <NameIO.h>
Classes
struct Algorithm
Public Types
typedef shared_ptr< NameIO >(* Constructor)(const rel::Interface &iface, const shared_ptr< Cipher > &cipher, const CipherKey &key)
typedef std::list< Algorithm > AlgorithmList
Public Member Functions
NameIO ()
virtual ~NameIO ()
virtual rel::Interface interface () const =0
void setChainedNameIV (bool enable)
bool getChainedNameIV () const
void setReverseEncryption (bool enable)
bool getReverseEncryption () const
std::string encodePath (const char *plaintextPath) const
std::string decodePath (const char *encodedPath) const
std::string encodePath (const char *plaintextPath, uint64_t *iv) const
std::string decodePath (const char *encodedPath, uint64_t *iv) const
virtual int maxEncodedNameLen (int plaintextNameLen) const =0
virtual int maxDecodedNameLen (int encodedNameLen) const =0
std::string encodeName (const char *plaintextName, int length) const
std::string decodeName (const char *encodedName, int length) const
Static Public Member Functions
static AlgorithmList GetAlgorithmList (bool includeHidden=false)
static shared_ptr< NameIO > New (const rel::Interface &iface, const shared_ptr< Cipher > &cipher, const CipherKey &key)
static shared_ptr< NameIO > New (const std::string &name, const shared_ptr< Cipher > &cipher, const CipherKey &key)
static bool Register (const char *name, const char *description, const rel::Interface &iface, Constructor constructor, bool hidden=false)
Protected Member Functions
virtual int encodeName (const char *plaintextName, int length, char *encodedName) const
virtual int decodeName (const char *encodedName, int length, char *plaintextName) const
virtual int encodeName (const char *plaintextName, int length, uint64_t *iv, char *encodedName) const =0
virtual int decodeName (const char *encodedName, int length, uint64_t *iv, char *plaintextName) const =0
Private Member Functions
std::string recodePath (const char *path, int(NameIO::*codingLen)(int) const, int(NameIO::*codingFunc)(const char *, int, uint64_t *, char *) const, uint64_t *iv) const
std::string _encodePath (const char *plaintextPath, uint64_t *iv) const
std::string _decodePath (const char *encodedPath, uint64_t *iv) const
std::string _encodeName (const char *plaintextName, int length) const
std::string _decodeName (const char *encodedName, int length) const
Private Attributes
bool chainedNameIV
bool reverseEncryption
Member Typedef Documentation
typedef std::list<Algorithm> NameIO::AlgorithmList
typedef shared_ptr<NameIO>(* NameIO::Constructor)(const rel::Interface &iface, const shared_ptr< Cipher > &cipher, const CipherKey &key)
Constructor & Destructor Documentation
NameIO::NameIO ()
NameIO::~NameIO () virtual
Member Function Documentation
std::string NameIO::_decodeName (const char * encodedName, int length) const private
References BUFFER_INIT, BUFFER_RESET, decodeName(), and maxDecodedNameLen().
Referenced by decodeName(), and encodeName().
std::string NameIO::_decodePath (const char * encodedPath, uint64_t * iv) const private
References chainedNameIV, decodeName(), maxDecodedNameLen(), and recodePath().
Referenced by decodePath(), and encodePath().
std::string NameIO::_encodeName (const char * plaintextName, int length) const private
References BUFFER_INIT, BUFFER_RESET, encodeName(), and maxEncodedNameLen().
Referenced by decodeName(), and encodeName().
std::string NameIO::_encodePath (const char * plaintextPath, uint64_t * iv) const private
References chainedNameIV, encodeName(), maxEncodedNameLen(), and recodePath().
Referenced by decodePath(), and encodePath().
std::string NameIO::decodeName (const char * encodedName, int length) const
References _decodeName(), _encodeName(), and getReverseEncryption().
Referenced by _decodeName(), _decodePath(), and decodeName().
int NameIO::decodeName (const char * encodedName, int length, char * plaintextName) const protected virtual
References decodeName().
virtual int NameIO::decodeName (const char * encodedName, int length, uint64_t * iv, char * plaintextName) const protected pure virtual
Implemented in BlockNameIO, StreamNameIO, NullNameIO, and YCNameIO.
std::string NameIO::decodePath (const char * encodedPath) const
std::string NameIO::decodePath (const char * encodedPath, uint64_t * iv) const
References _decodePath(), _encodePath(), and getReverseEncryption().
std::string NameIO::encodeName (const char * plaintextName, int length) const
References _decodeName(), _encodeName(), and getReverseEncryption().
Referenced by _encodeName(), _encodePath(), and encodeName().
int NameIO::encodeName (const char * plaintextName, int length, char * encodedName) const protected virtual
References encodeName().
virtual int NameIO::encodeName (const char * plaintextName, int length, uint64_t * iv, char * encodedName) const protected pure virtual
Implemented in BlockNameIO, StreamNameIO, NullNameIO, and YCNameIO.
std::string NameIO::encodePath (const char * plaintextPath) const
std::string NameIO::encodePath (const char * plaintextPath, uint64_t * iv) const
References _decodePath(), _encodePath(), and getReverseEncryption().
list< NameIO::Algorithm > NameIO::GetAlgorithmList (bool includeHidden = false) static
References AddSymbolReferences(), NameIO::Algorithm::description, gNameIOMap, NameIO::Algorithm::iface, and NameIO::Algorithm::name.
Referenced by selectNameCoding().
bool NameIO::getChainedNameIV () const
References chainedNameIV.
bool NameIO::getReverseEncryption () const
References reverseEncryption.
Referenced by decodeName(), decodePath(), encodeName(), and encodePath().
virtual rel::Interface NameIO::interface () const pure virtual
Implemented in BlockNameIO, StreamNameIO, NullNameIO, and YCNameIO.
virtual int NameIO::maxDecodedNameLen (int encodedNameLen) const pure virtual
Implemented in BlockNameIO, StreamNameIO, NullNameIO, and YCNameIO.
Referenced by _decodeName(), and _decodePath().
virtual int NameIO::maxEncodedNameLen (int plaintextNameLen) const pure virtual
Implemented in BlockNameIO, StreamNameIO, NullNameIO, and YCNameIO.
Referenced by _encodeName(), and _encodePath().
shared_ptr< NameIO > NameIO::New (const rel::Interface & iface, const shared_ptr< Cipher > & cipher, const CipherKey & key) static
References gNameIOMap.
Referenced by youcrypt::YoucryptFolder::createAtPath(), createV6Config(), initFS(), youcrypt::YoucryptFolder::loadConfigAtPath(), and showFSInfo().
shared_ptr< NameIO > NameIO::New (const std::string & name, const shared_ptr< Cipher > & cipher, const CipherKey & key) static
References gNameIOMap.
std::string NameIO::recodePath (const char * path, int(NameIO::*)(int) const codingLen, int(NameIO::*)(const char *, int, uint64_t *, char *) const codingFunc, uint64_t * iv) const private
References BUFFER_INIT, and BUFFER_RESET.
Referenced by _decodePath(), and _encodePath().
bool NameIO::Register (const char * name, const char * description, const rel::Interface & iface, Constructor constructor, bool hidden = false) static
References NameIOAlg::constructor, NameIOAlg::description, gNameIOMap, NameIOAlg::hidden, and NameIOAlg::iface.
void NameIO::setChainedNameIV (bool enable)
References chainedNameIV.
void NameIO::setReverseEncryption (bool enable)
References reverseEncryption.
Member Data Documentation
bool NameIO::chainedNameIV private
Referenced by _decodePath(), _encodePath(), getChainedNameIV(), and setChainedNameIV().
bool NameIO::reverseEncryption private
Referenced by getReverseEncryption(), and setReverseEncryption().
The documentation for this class was generated from the following files:
NameIO.h
NameIO.cpp