Youcrypt/EncFS: ConfigVar Class Reference
ConfigVar Class Reference
#include <ConfigVar.h>
Classes
struct ConfigVarData
Public Member Functions
ConfigVar ()
ConfigVar (const std::string &buffer)
ConfigVar (const ConfigVar &src)
~ConfigVar ()
ConfigVar & operator= (const ConfigVar &src)
void resetOffset ()
int read (unsigned char *buffer, int size) const
int write (const unsigned char *data, int size)
int readInt () const
int readInt (int defaultValue) const
void writeInt (int value)
bool readBool (bool defaultValue) const
void writeString (const char *data, int size)
int size () const
const char * buffer () const
int at () const
Private Attributes
shared_ptr< ConfigVarData > pd
Constructor & Destructor Documentation
ConfigVar::ConfigVar ()
References pd.
ConfigVar::ConfigVar (const std::string & buffer)
References pd.
ConfigVar::ConfigVar (const ConfigVar & src)
References pd.
ConfigVar::~ConfigVar ()
References pd.
Member Function Documentation
int ConfigVar::at () const
References pd.
Referenced by readInt().
const char * ConfigVar::buffer () const
References pd.
Referenced by readInt(), and ConfigReader::save().
ConfigVar & ConfigVar::operator= (const ConfigVar & src)
References pd.
int ConfigVar::read (unsigned char * buffer, int size) const
References MIN, and pd.
Referenced by operator>>().
bool ConfigVar::readBool (bool defaultValue) const
References readInt().
int ConfigVar::readInt () const
References at(), buffer(), pd, and size().
Referenced by ConfigReader::loadFromVar(), operator>>(), readBool(), and readInt().
int ConfigVar::readInt (int defaultValue) const
References at(), readInt(), and size().
void ConfigVar::resetOffset ()
References pd.
Referenced by ConfigReader::loadFromVar().
int ConfigVar::size () const
References pd.
Referenced by readInt(), and ConfigReader::save().
int ConfigVar::write (const unsigned char * data, int size)
References pd.
Referenced by ConfigReader::load(), ConfigReader::toVar(), writeInt(), and writeString().
void ConfigVar::writeInt (int value)
References write().
Referenced by operator<<(), ConfigReader::toVar(), and writeString().
void ConfigVar::writeString (const char * data, int size)
References write(), and writeInt().
Referenced by operator<<().
Member Data Documentation
shared_ptr<ConfigVarData> ConfigVar::pd private
Referenced by at(), buffer(), ConfigVar(), operator=(), read(), readInt(), resetOffset(), size(), write(), and ~ConfigVar().
The documentation for this class was generated from the following files:
ConfigVar.h
ConfigVar.cpp