Youcrypt/EncFS: Cipher Class Reference
Cipher Class Reference
#include <Cipher.h>
Classes
struct CipherAlgorithm
Public Types
typedef boost::shared_ptr
< Cipher >(* CipherConstructor)(const rel::Interface &iface, int keyLenBits)
typedef std::list
< CipherAlgorithm > AlgorithmList
Public Member Functions
Cipher ()
virtual ~Cipher ()
virtual rel::Interface interface () const =0
virtual CipherKey newKey (const char *password, int passwdLength, int &iterationCount, long desiredFunctionDuration, const unsigned char *salt, int saltLen)=0
virtual CipherKey newKey (const char *password, int passwdLength)=0
virtual CipherKey newRandomKey ()=0
virtual CipherKey readKey (const unsigned char *data, const CipherKey &encodingKey, bool checkKey=true)=0
virtual void writeKey (const CipherKey &key, unsigned char *data, const CipherKey &encodingKey)=0
virtual std::string encodeAsString (const CipherKey &key, const CipherKey &encodingKey)
virtual bool compareKey (const CipherKey &A, const CipherKey &B) const =0
virtual int keySize () const =0
virtual int encodedKeySize () const =0
virtual int cipherBlockSize () const =0
virtual bool randomize (unsigned char *buf, int len, bool strongRandom) const =0
virtual uint64_t MAC_64 (const unsigned char *src, int len, const CipherKey &key, uint64_t *chainedIV=0) const =0
unsigned int MAC_32 (const unsigned char *src, int len, const CipherKey &key, uint64_t *chainedIV=0) const
unsigned int MAC_16 (const unsigned char *src, int len, const CipherKey &key, uint64_t *chainedIV=0) const
virtual bool streamEncode (unsigned char *data, int len, uint64_t iv64, const CipherKey &key) const =0
virtual bool streamDecode (unsigned char *data, int len, uint64_t iv64, const CipherKey &key) const =0
virtual bool nameEncode (unsigned char *data, int len, uint64_t iv64, const CipherKey &key) const
virtual bool nameDecode (unsigned char *data, int len, uint64_t iv64, const CipherKey &key) const
virtual bool blockEncode (unsigned char *buf, int size, uint64_t iv64, const CipherKey &key) const =0
virtual bool blockDecode (unsigned char *buf, int size, uint64_t iv64, const CipherKey &key) const =0
Static Public Member Functions
static AlgorithmList GetAlgorithmList (bool includeHidden=false)
static boost::shared_ptr< Cipher > New (const rel::Interface &iface, int keyLen=-1)
static boost::shared_ptr< Cipher > New (const std::string &cipherName, int keyLen=-1)
static bool Register (const char *cipherName, const char *description, const rel::Interface &iface, CipherConstructor constructor, bool hidden=false)
static bool Register (const char *cipherName, const char *description, const rel::Interface &iface, const Range &keyLength, const Range &blockSize, CipherConstructor constructor, bool hidden=false)
Member Typedef Documentation
typedef std::list<CipherAlgorithm> Cipher::AlgorithmList
typedef boost::shared_ptr<Cipher>(* Cipher::CipherConstructor)(const rel::Interface &iface, int keyLenBits)
Constructor & Destructor Documentation
Cipher::Cipher ()
Cipher::~Cipher () virtual
Member Function Documentation
virtual bool Cipher::blockDecode (unsigned char * buf, int size, uint64_t iv64, const CipherKey & key) const pure virtual
Implemented in SSL_Cipher, and NullCipher.
virtual bool Cipher::blockEncode (unsigned char * buf, int size, uint64_t iv64, const CipherKey & key) const pure virtual
Implemented in SSL_Cipher, and NullCipher.
virtual int Cipher::cipherBlockSize () const pure virtual
Implemented in SSL_Cipher, and NullCipher.
virtual bool Cipher::compareKey (const CipherKey & A, const CipherKey & B) const pure virtual
Implemented in SSL_Cipher, and NullCipher.
string Cipher::encodeAsString (const CipherKey & key, const CipherKey & encodingKey) virtual
References B256ToB64Bytes(), B64ToAscii(), and changeBase2().
virtual int Cipher::encodedKeySize () const pure virtual
Implemented in SSL_Cipher, and NullCipher.
std::list< Cipher::CipherAlgorithm > Cipher::GetAlgorithmList (bool includeHidden = false) static
References AddSymbolReferences(), Cipher::CipherAlgorithm::blockSize, Cipher::CipherAlgorithm::description, gCipherMap, Cipher::CipherAlgorithm::iface, Cipher::CipherAlgorithm::keyLength, and Cipher::CipherAlgorithm::name.
Referenced by findCipherAlgorithm(), main(), and selectCipherAlgorithm().
virtual rel::Interface Cipher::interface () const pure virtual
Implemented in SSL_Cipher, and NullCipher.
virtual int Cipher::keySize () const pure virtual
Implemented in SSL_Cipher, and NullCipher.
unsigned int Cipher::MAC_16 (const unsigned char * src, int len, const CipherKey & key, uint64_t * chainedIV = 0) const
unsigned int Cipher::MAC_32 (const unsigned char * src, int len, const CipherKey & key, uint64_t * chainedIV = 0) const
virtual uint64_t Cipher::MAC_64 (const unsigned char * src, int len, const CipherKey & key, uint64_t * chainedIV = 0) const pure virtual
Implemented in SSL_Cipher, and NullCipher.
bool Cipher::nameDecode (unsigned char * data, int len, uint64_t iv64, const CipherKey & key) const virtual
bool Cipher::nameEncode (unsigned char * data, int len, uint64_t iv64, const CipherKey & key) const virtual
shared_ptr< Cipher > Cipher::New (const rel::Interface & iface, int keyLen = -1) static
References gCipherMap.
Referenced by createV6Config(), do_chpasswd(), EncFSConfig::getCipher(), main(), and showFSInfo().
shared_ptr< Cipher > Cipher::New (const std::string & cipherName, int keyLen = -1) static
References gCipherMap.
virtual CipherKey Cipher::newKey (const char * password, int passwdLength, int & iterationCount, long desiredFunctionDuration, const unsigned char * salt, int saltLen) pure virtual
Implemented in SSL_Cipher, and NullCipher.
virtual CipherKey Cipher::newKey (const char * password, int passwdLength) pure virtual
Implemented in SSL_Cipher, and NullCipher.
virtual CipherKey Cipher::newRandomKey () pure virtual
Implemented in SSL_Cipher, and NullCipher.
virtual bool Cipher::randomize (unsigned char * buf, int len, bool strongRandom) const pure virtual
Implemented in SSL_Cipher, and NullCipher.
virtual CipherKey Cipher::readKey (const unsigned char * data, const CipherKey & encodingKey, bool checkKey = true) pure virtual
Implemented in SSL_Cipher, and NullCipher.
bool Cipher::Register (const char * cipherName, const char * description, const rel::Interface & iface, CipherConstructor constructor, bool hidden = false) static
bool Cipher::Register (const char * cipherName, const char * description, const rel::Interface & iface, const Range & keyLength, const Range & blockSize, CipherConstructor constructor, bool hidden = false) static
References CipherAlg::blockSize, CipherAlg::constructor, CipherAlg::description, gCipherMap, CipherAlg::hidden, CipherAlg::iface, and CipherAlg::keyLength.
virtual bool Cipher::streamDecode (unsigned char * data, int len, uint64_t iv64, const CipherKey & key) const pure virtual
Implemented in SSL_Cipher, and NullCipher.
virtual bool Cipher::streamEncode (unsigned char * data, int len, uint64_t iv64, const CipherKey & key) const pure virtual
Implemented in SSL_Cipher, and NullCipher.
virtual void Cipher::writeKey (const CipherKey & key, unsigned char * data, const CipherKey & encodingKey) pure virtual
Implemented in SSL_Cipher, and NullCipher.
The documentation for this class was generated from the following files:
Cipher.h
Cipher.cpp