Youcrypt/EncFS: SSL_Cipher Class Reference
SSL_Cipher Class Reference
#include <SSL_Cipher.h>
Public Member Functions
SSL_Cipher (const rel::Interface &iface, const rel::Interface &realIface, const EVP_CIPHER *blockCipher, const EVP_CIPHER *streamCipher, int keyLength)
virtual ~SSL_Cipher ()
virtual rel::Interface interface () const
virtual CipherKey newKey (const char *password, int passwdLength, int &iterationCount, long desiredDuration, const unsigned char *salt, int saltLen)
virtual CipherKey newKey (const char *password, int passwdLength)
virtual CipherKey newRandomKey ()
virtual CipherKey readKey (const unsigned char *data, const CipherKey &encodingKey, bool checkKey)
virtual void writeKey (const CipherKey &key, unsigned char *data, const CipherKey &encodingKey)
virtual bool compareKey (const CipherKey &A, const CipherKey &B) const
virtual int keySize () const
virtual int encodedKeySize () const
virtual int cipherBlockSize () const
virtual bool randomize (unsigned char *buf, int len, bool strongRandom) const
virtual uint64_t MAC_64 (const unsigned char *src, int len, const CipherKey &key, uint64_t *augment) const
virtual bool streamEncode (unsigned char *in, int len, uint64_t iv64, const CipherKey &key) const
virtual bool streamDecode (unsigned char *in, int len, uint64_t iv64, const CipherKey &key) const
virtual bool blockEncode (unsigned char *buf, int size, uint64_t iv64, const CipherKey &key) const
virtual bool blockDecode (unsigned char *buf, int size, uint64_t iv64, const CipherKey &key) const
Public Member Functions inherited from Cipher
Cipher ()
virtual ~Cipher ()
virtual std::string encodeAsString (const CipherKey &key, const CipherKey &encodingKey)
unsigned int MAC_32 (const unsigned char *src, int len, const CipherKey &key, uint64_t *chainedIV=0) const
unsigned int MAC_16 (const unsigned char *src, int len, const CipherKey &key, uint64_t *chainedIV=0) const
virtual bool nameEncode (unsigned char *data, int len, uint64_t iv64, const CipherKey &key) const
virtual bool nameDecode (unsigned char *data, int len, uint64_t iv64, const CipherKey &key) const
Static Public Member Functions
static bool Enabled ()
Static Public Member Functions inherited from Cipher
static AlgorithmList GetAlgorithmList (bool includeHidden=false)
static boost::shared_ptr< Cipher > New (const rel::Interface &iface, int keyLen=-1)
static boost::shared_ptr< Cipher > New (const std::string &cipherName, int keyLen=-1)
static bool Register (const char *cipherName, const char *description, const rel::Interface &iface, CipherConstructor constructor, bool hidden=false)
static bool Register (const char *cipherName, const char *description, const rel::Interface &iface, const Range &keyLength, const Range &blockSize, CipherConstructor constructor, bool hidden=false)
Private Member Functions
void setIVec (unsigned char *ivec, uint64_t seed, const shared_ptr< SSLKey > &key) const
void setIVec_old (unsigned char *ivec, unsigned int seed, const shared_ptr< SSLKey > &key) const
Private Attributes
rel::Interface iface
rel::Interface realIface
const EVP_CIPHER * _blockCipher
const EVP_CIPHER * _streamCipher
unsigned int _keySize
unsigned int _ivLength
Additional Inherited Members
Public Types inherited from Cipher
typedef boost::shared_ptr
< Cipher >(* CipherConstructor)(const rel::Interface &iface, int keyLenBits)
typedef std::list
< CipherAlgorithm > AlgorithmList
Constructor & Destructor Documentation
SSL_Cipher::SSL_Cipher (const rel::Interface & iface, const rel::Interface & realIface, const EVP_CIPHER * blockCipher, const EVP_CIPHER * streamCipher, int keyLength)
References CipherInfo, rel::Interface::current(), and rel::Interface::name().
SSL_Cipher::~SSL_Cipher () virtual
Member Function Documentation
bool SSL_Cipher::blockDecode (unsigned char * buf, int size, uint64_t iv64, const CipherKey & key) const virtual
Implements Cipher.
References MAX_IVLENGTH.
bool SSL_Cipher::blockEncode (unsigned char * buf, int size, uint64_t iv64, const CipherKey & key) const virtual
Implements Cipher.
References MAX_IVLENGTH.
int SSL_Cipher::cipherBlockSize () const virtual
Implements Cipher.
bool SSL_Cipher::compareKey (const CipherKey & A, const CipherKey & B) const virtual
Implements Cipher.
bool SSL_Cipher::Enabled () static
int SSL_Cipher::encodedKeySize () const virtual
Implements Cipher.
References KEY_CHECKSUM_BYTES.
Interface SSL_Cipher::interface () const virtual
Implements Cipher.
int SSL_Cipher::keySize () const virtual
Implements Cipher.
uint64_t SSL_Cipher::MAC_64 (const unsigned char * src, int len, const CipherKey & key, uint64_t * augment) const virtual
Implements Cipher.
References _checksum_64().
CipherKey SSL_Cipher::newKey (const char * password, int passwdLength, int & iterationCount, long desiredDuration, const unsigned char * salt, int saltLen) virtual
Implements Cipher.
References initKey(), KeyData(), and TimedPBKDF2().
CipherKey SSL_Cipher::newKey (const char * password, int passwdLength) virtual
Implements Cipher.
References BytesToKey(), rel::Interface::current(), initKey(), IVData(), and KeyData().
CipherKey SSL_Cipher::newRandomKey () virtual
Implements Cipher.
References initKey(), KeyData(), and MAX_KEYLENGTH.
bool SSL_Cipher::randomize (unsigned char * buf, int len, bool strongRandom) const virtual
Implements Cipher.
CipherKey SSL_Cipher::readKey (const unsigned char * data, const CipherKey & encodingKey, bool checkKey) virtual
Implements Cipher.
References initKey(), KEY_CHECKSUM_BYTES, MAX_IVLENGTH, and MAX_KEYLENGTH.
void SSL_Cipher::setIVec (unsigned char * ivec, uint64_t seed, const shared_ptr< SSLKey > & key) const private
References rel::Interface::current(), and IVData().
void SSL_Cipher::setIVec_old (unsigned char * ivec, unsigned int seed, const shared_ptr< SSLKey > & key) const private
For backward compatibility. A watermark attack was discovered against this IV setup. If an attacker could get a victim to store a carefully crafted file, they could later determine if the victim had the file in encrypted storage (without decrypting the file).
References IVData().
bool SSL_Cipher::streamDecode (unsigned char * in, int len, uint64_t iv64, const CipherKey & key) const virtual
Implements Cipher.
References flipBytes(), MAX_IVLENGTH, and unshuffleBytes().
bool SSL_Cipher::streamEncode (unsigned char * in, int len, uint64_t iv64, const CipherKey & key) const virtual
Implements Cipher.
References flipBytes(), MAX_IVLENGTH, and shuffleBytes().
void SSL_Cipher::writeKey (const CipherKey & key, unsigned char * data, const CipherKey & encodingKey) virtual
Implements Cipher.
References KEY_CHECKSUM_BYTES, MAX_IVLENGTH, and MAX_KEYLENGTH.
Member Data Documentation
const EVP_CIPHER* SSL_Cipher::_blockCipher private
unsigned int SSL_Cipher::_ivLength private
unsigned int SSL_Cipher::_keySize private
const EVP_CIPHER* SSL_Cipher::_streamCipher private
rel::Interface SSL_Cipher::iface private
rel::Interface SSL_Cipher::realIface private
The documentation for this class was generated from the following files:
SSL_Cipher.h
SSL_Cipher.cpp