Youcrypt/EncFS: StreamNameIO Class Reference
StreamNameIO Class Reference
#include <StreamNameIO.h>
Public Member Functions
StreamNameIO (const rel::Interface &iface, const shared_ptr< Cipher > &cipher, const CipherKey &key)
virtual ~StreamNameIO ()
virtual rel::Interface interface () const
virtual int maxEncodedNameLen (int plaintextNameLen) const
virtual int maxDecodedNameLen (int encodedNameLen) const
Public Member Functions inherited from NameIO
NameIO ()
virtual ~NameIO ()
void setChainedNameIV (bool enable)
bool getChainedNameIV () const
void setReverseEncryption (bool enable)
bool getReverseEncryption () const
std::string encodePath (const char *plaintextPath) const
std::string decodePath (const char *encodedPath) const
std::string encodePath (const char *plaintextPath, uint64_t *iv) const
std::string decodePath (const char *encodedPath, uint64_t *iv) const
std::string encodeName (const char *plaintextName, int length) const
std::string decodeName (const char *encodedName, int length) const
Static Public Member Functions
static rel::Interface CurrentInterface ()
static bool Enabled ()
Static Public Member Functions inherited from NameIO
static AlgorithmList GetAlgorithmList (bool includeHidden=false)
static shared_ptr< NameIO > New (const rel::Interface &iface, const shared_ptr< Cipher > &cipher, const CipherKey &key)
static shared_ptr< NameIO > New (const std::string &name, const shared_ptr< Cipher > &cipher, const CipherKey &key)
static bool Register (const char *name, const char *description, const rel::Interface &iface, Constructor constructor, bool hidden=false)
Protected Member Functions
virtual int encodeName (const char *plaintextName, int length, uint64_t *iv, char *encodedName) const
virtual int decodeName (const char *encodedName, int length, uint64_t *iv, char *plaintextName) const
Protected Member Functions inherited from NameIO
virtual int encodeName (const char *plaintextName, int length, char *encodedName) const
virtual int decodeName (const char *encodedName, int length, char *plaintextName) const
Private Attributes
int _interface
shared_ptr< Cipher > _cipher
CipherKey _key
Additional Inherited Members
Public Types inherited from NameIO
typedef shared_ptr< NameIO >(* Constructor)(const rel::Interface &iface, const shared_ptr< Cipher > &cipher, const CipherKey &key)
typedef std::list< Algorithm > AlgorithmList
Constructor & Destructor Documentation
StreamNameIO::StreamNameIO (const rel::Interface & iface, const shared_ptr< Cipher > & cipher, const CipherKey & key)
StreamNameIO::~StreamNameIO () virtual
Member Function Documentation
Interface StreamNameIO::CurrentInterface () static
Referenced by interface(), and runTests().
int StreamNameIO::decodeName (const char * encodedName, int length, uint64_t * iv, char * plaintextName) const protected virtual
Implements NameIO.
References _cipher, _interface, _key, AsciiToB64(), B64ToB256Bytes(), BUFFER_INIT, BUFFER_RESET, and changeBase2Inline().
bool StreamNameIO::Enabled () static
int StreamNameIO::encodeName (const char * plaintextName, int length, uint64_t * iv, char * encodedName) const protected virtual
Implements NameIO.
References _cipher, _interface, _key, B256ToB64Bytes(), B64ToAscii(), and changeBase2Inline().
Interface StreamNameIO::interface () const virtual
Implements NameIO.
References CurrentInterface().
int StreamNameIO::maxDecodedNameLen (int encodedNameLen) const virtual
Implements NameIO.
References B64ToB256Bytes().
int StreamNameIO::maxEncodedNameLen (int plaintextNameLen) const virtual
Implements NameIO.
References B256ToB64Bytes().
Member Data Documentation
shared_ptr<Cipher> StreamNameIO::_cipher private
Referenced by decodeName(), and encodeName().
int StreamNameIO::_interface private
Referenced by decodeName(), and encodeName().
CipherKey StreamNameIO::_key private
Referenced by decodeName(), and encodeName().
The documentation for this class was generated from the following files:
StreamNameIO.h
StreamNameIO.cpp