Youcrypt/EncFS: BlockFileIO Class Reference
BlockFileIO Class Reference
#include <BlockFileIO.h>
Public Member Functions
BlockFileIO (int blockSize, const FSConfigPtr &cfg)
virtual ~BlockFileIO ()
virtual ssize_t read (const IORequest &req) const
virtual bool write (const IORequest &req)
virtual int blockSize () const
Public Member Functions inherited from FileIO
FileIO ()
virtual ~FileIO ()
virtual rel::Interface interface () const =0
virtual void setFileName (const char *fileName)=0
virtual const char * getFileName () const =0
virtual bool setIV (uint64_t iv)
virtual int open (int flags)=0
virtual int getAttr (struct stat *stbuf) const =0
virtual off_t getSize () const =0
virtual int truncate (off_t size)=0
virtual bool isWritable () const =0
Protected Member Functions
int truncate (off_t size, FileIO *base)
void padFile (off_t oldSize, off_t newSize, bool forceWrite)
virtual ssize_t readOneBlock (const IORequest &req) const =0
virtual bool writeOneBlock (const IORequest &req)=0
ssize_t cacheReadOneBlock (const IORequest &req) const
bool cacheWriteOneBlock (const IORequest &req)
Protected Attributes
int _blockSize
bool _allowHoles
IORequest _cache
Constructor & Destructor Documentation
BlockFileIO::BlockFileIO (int blockSize, const FSConfigPtr & cfg)
References _blockSize, _cache, and IORequest::data.
BlockFileIO::~BlockFileIO () virtual
References _blockSize, _cache, clearCache(), and IORequest::data.
Member Function Documentation
int BlockFileIO::blockSize () const virtual
Reimplemented from FileIO.
References _blockSize.
Referenced by MACFileIO::getAttr(), MACFileIO::getSize(), MACFileIO::readOneBlock(), CipherFileIO::readOneBlock(), MACFileIO::truncate(), MACFileIO::writeOneBlock(), and CipherFileIO::writeOneBlock().
ssize_t BlockFileIO::cacheReadOneBlock (const IORequest & req) const protected
References _blockSize, _cache, clearCache(), IORequest::data, IORequest::dataLen, IORequest::offset, and readOneBlock().
Referenced by padFile(), read(), truncate(), and write().
bool BlockFileIO::cacheWriteOneBlock (const IORequest & req) protected
References _blockSize, _cache, clearCache(), IORequest::data, IORequest::dataLen, IORequest::offset, and writeOneBlock().
Referenced by padFile(), truncate(), and write().
void BlockFileIO::padFile (off_t oldSize, off_t newSize, bool forceWrite) protected
References _allowHoles, _blockSize, MemoryPool::allocate(), cacheReadOneBlock(), cacheWriteOneBlock(), MemBlock::data, IORequest::data, IORequest::dataLen, IORequest::offset, and MemoryPool::release().
Referenced by truncate(), and write().
ssize_t BlockFileIO::read (const IORequest & req) const virtual
Implements FileIO.
References _blockSize, MemoryPool::allocate(), cacheReadOneBlock(), MemBlock::data, IORequest::data, IORequest::dataLen, min(), IORequest::offset, and MemoryPool::release().
virtual ssize_t BlockFileIO::readOneBlock (const IORequest & req) const protected pure virtual
Implemented in CipherFileIO, and MACFileIO.
Referenced by cacheReadOneBlock().
int BlockFileIO::truncate (off_t size, FileIO * base) protected
References _, _blockSize, MemoryPool::allocate(), cacheReadOneBlock(), cacheWriteOneBlock(), MemBlock::data, IORequest::data, IORequest::dataLen, FileIO::getSize(), IORequest::offset, padFile(), MemoryPool::release(), and FileIO::truncate().
bool BlockFileIO::write (const IORequest & req) virtual
Implements FileIO.
References _blockSize, MemoryPool::allocate(), cacheReadOneBlock(), cacheWriteOneBlock(), MemBlock::data, IORequest::data, IORequest::dataLen, FileIO::getSize(), min(), IORequest::offset, padFile(), and MemoryPool::release().
virtual bool BlockFileIO::writeOneBlock (const IORequest & req) protected pure virtual
Implemented in CipherFileIO, and MACFileIO.
Referenced by cacheWriteOneBlock().
Member Data Documentation
bool BlockFileIO::_allowHoles protected
Referenced by CipherFileIO::blockRead(), padFile(), and MACFileIO::readOneBlock().
int BlockFileIO::_blockSize protected
Referenced by BlockFileIO(), blockSize(), cacheReadOneBlock(), cacheWriteOneBlock(), padFile(), read(), truncate(), write(), and ~BlockFileIO().
IORequest BlockFileIO::_cache mutable protected
Referenced by BlockFileIO(), cacheReadOneBlock(), cacheWriteOneBlock(), and ~BlockFileIO().
The documentation for this class was generated from the following files:
BlockFileIO.h
BlockFileIO.cpp