Youcrypt/EncFS: encfs.h File Reference
encfs.h File Reference
#include "config.h"
#include <fuse.h>
#include <unistd.h>
#include <cerrno>
Functions
static __inline int setfsuid (uid_t uid)
static __inline int setfsgid (gid_t gid)
int encfs_getattr (const char *path, struct stat *stbuf)
int encfs_fgetattr (const char *path, struct stat *stbuf, struct fuse_file_info *fi)
int encfs_readlink (const char *path, char *buf, size_t size)
int encfs_getdir (const char *path, fuse_dirh_t h, fuse_dirfil_t filler)
int encfs_mknod (const char *path, mode_t mode, dev_t rdev)
int encfs_mkdir (const char *path, mode_t mode)
int encfs_unlink (const char *path)
int encfs_rmdir (const char *path)
int encfs_symlink (const char *from, const char *to)
int encfs_rename (const char *from, const char *to)
int encfs_link (const char *from, const char *to)
int encfs_chmod (const char *path, mode_t mode)
int encfs_chown (const char *path, uid_t uid, gid_t gid)
int encfs_truncate (const char *path, off_t size)
int encfs_ftruncate (const char *path, off_t size, struct fuse_file_info *fi)
int encfs_utime (const char *path, struct utimbuf *buf)
int encfs_open (const char *path, struct fuse_file_info *info)
int encfs_release (const char *path, struct fuse_file_info *info)
int encfs_read (const char *path, char *buf, size_t size, off_t offset, struct fuse_file_info *info)
int encfs_write (const char *path, const char *buf, size_t size, off_t offset, struct fuse_file_info *info)
int encfs_statfs (const char *, struct statvfs *fst)
int encfs_flush (const char *, struct fuse_file_info *info)
int encfs_fsync (const char *path, int flags, struct fuse_file_info *info)
int encfs_utimens (const char *path, const struct timespec ts[2])
Function Documentation
int encfs_chmod (const char * path, mode_t mode)
References _do_chmod(), and withCipherPath().
Referenced by main().
int encfs_chown (const char * path, uid_t uid, gid_t gid)
References _do_chown(), and withCipherPath().
Referenced by main().
int encfs_fgetattr (const char * path, struct stat * stbuf, struct fuse_file_info * fi)
References _do_getattr(), and withFileNode().
Referenced by main().
int encfs_flush (const char * , struct fuse_file_info * info)
References _do_flush(), and withFileNode().
Referenced by main().
int encfs_fsync (const char * path, int flags, struct fuse_file_info * info)
References _do_fsync(), and withFileNode().
Referenced by main().
int encfs_ftruncate (const char * path, off_t size, struct fuse_file_info * fi)
References _do_truncate(), and withFileNode().
Referenced by main().
int encfs_getattr (const char * path, struct stat * stbuf)
References _do_getattr(), and withFileNode().
Referenced by main().
int encfs_getdir (const char * path, fuse_dirh_t h, fuse_dirfil_t filler)
References context(), ESUCCESS, EncFS_Context::getRoot(), Info, DirTraverse::nextPlaintextName(), and DirTraverse::valid().
Referenced by main().
int encfs_link (const char * from, const char * to)
References context(), and EncFS_Context::getRoot().
Referenced by main().
int encfs_mkdir (const char * path, mode_t mode)
References context(), EncFS_Context::getRoot(), parentDirectory(), and EncFS_Context::publicFilesystem.
Referenced by main().
int encfs_mknod (const char * path, mode_t mode, dev_t rdev)
References context(), EncFS_Context::getRoot(), Info, and EncFS_Context::publicFilesystem.
Referenced by main().
int encfs_open (const char * path, struct fuse_file_info * info)
References context(), ESUCCESS, EncFS_Context::getRoot(), Info, and EncFS_Context::putNode().
Referenced by main().
int encfs_read (const char * path, char * buf, size_t size, off_t offset, struct fuse_file_info * info)
References _do_read(), and withFileNode().
Referenced by main().
int encfs_readlink (const char * path, char * buf, size_t size)
References _do_readlink(), and withCipherPath().
Referenced by main().
int encfs_release (const char * path, struct fuse_file_info * info)
References context(), EncFS_Context::eraseNode(), and ESUCCESS.
Referenced by main().
int encfs_rename (const char * from, const char * to)
References context(), and EncFS_Context::getRoot().
Referenced by main().
int encfs_rmdir (const char * path)
References _do_rmdir(), and withCipherPath().
Referenced by main().
int encfs_statfs (const char * , struct statvfs * fst)
References context(), Info, and EncFS_Context::rootCipherDir.
Referenced by main().
int encfs_symlink (const char * from, const char * to)
References context(), ESUCCESS, EncFS_Context::getRoot(), Info, EncFS_Context::publicFilesystem, setfsgid(), and setfsuid().
Referenced by main().
int encfs_truncate (const char * path, off_t size)
References _do_truncate(), and withFileNode().
Referenced by main().
int encfs_unlink (const char * path)
References context(), and EncFS_Context::getRoot().
Referenced by main().
int encfs_utime (const char * path, struct utimbuf * buf)
References _do_utime(), and withCipherPath().
Referenced by main().
int encfs_utimens (const char * path, const struct timespec ts[2])
References _do_utimens(), and withCipherPath().
Referenced by main().
int encfs_write (const char * path, const char * buf, size_t size, off_t offset, struct fuse_file_info * info)
References _do_write(), and withFileNode().
Referenced by main().
static __inline int setfsgid (gid_t gid) static
Referenced by encfs_symlink(), DirNode::mkdir(), and FileNode::mknod().
static __inline int setfsuid (uid_t uid) static
Referenced by encfs_symlink(), DirNode::mkdir(), and FileNode::mknod().