Youcrypt/EncFS: encfsctl.cpp File Reference
encfsctl.cpp File Reference
#include "encfs.h"
#include "autosprintf.h"
#include "config.h"
#include "FileUtils.h"
#include "Cipher.h"
#include "Context.h"
#include "FileNode.h"
#include "DirNode.h"
#include <rlog/rlog.h>
#include <rlog/StdioNode.h>
#include <rlog/RLogChannel.h>
#include <iostream>
#include <string>
#include <getopt.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include "i18n.h"
#include <boost/scoped_array.hpp>
Classes
struct CommandOpts
class WriteOutput
Functions
static int showInfo (int argc, char **argv)
static int showVersion (int argc, char **argv)
static int chpasswd (int argc, char **argv)
static int chpasswdAutomaticly (int argc, char **argv)
static int cmd_ls (int argc, char **argv)
static int cmd_decode (int argc, char **argv)
static int cmd_encode (int argc, char **argv)
static int cmd_showcruft (int argc, char **argv)
static int cmd_cat (int argc, char **argv)
static int cmd_export (int argc, char **argv)
static int cmd_showKey (int argc, char **argv)
static void usage (const char *name)
static bool checkDir (string &rootDir)
static RootPtr initRootInfo (int &argc, char **&argv)
static RootPtr initRootInfo (const char *crootDir)
template<typename T >
int processContents (const shared_ptr< EncFS_Root > &rootInfo, const char *path, T &op)
static int copyLink (const struct stat &stBuf, const shared_ptr< EncFS_Root > &rootInfo, const string &cpath, const string &destName)
static int copyContents (const shared_ptr< EncFS_Root > &rootInfo, const char *encfsName, const char *targetName)
static bool endsWith (const string &str, char ch)
static int traverseDirs (const shared_ptr< EncFS_Root > &rootInfo, string volumeDir, string destDir)
int showcruft (const shared_ptr< EncFS_Root > &rootInfo, const char *dirName)
static int do_chpasswd (bool useStdin, int argc, char **argv)
int main (int argc, char **argv)
Variables
struct CommandOpts commands []
Function Documentation
static bool checkDir (string & rootDir) static
References _, and isDirectory().
Referenced by cmd_export(), do_chpasswd(), initRootInfo(), and showInfo().
static int chpasswd (int argc, char ** argv) static
References do_chpasswd().
static int chpasswdAutomaticly (int argc, char ** argv) static
References do_chpasswd().
static int cmd_cat (int argc, char ** argv) static
References initRootInfo(), and processContents().
static int cmd_decode (int argc, char ** argv) static
References initRootInfo().
static int cmd_encode (int argc, char ** argv) static
References initRootInfo().
static int cmd_export (int argc, char ** argv) static
References checkDir(), initRootInfo(), traverseDirs(), and userAllowMkdir().
static int cmd_ls (int argc, char ** argv) static
References initRootInfo(), DirTraverse::nextPlaintextName(), and DirTraverse::valid().
static int cmd_showcruft (int argc, char ** argv) static
References initRootInfo(), and showcruft().
static int cmd_showKey (int argc, char ** argv) static
References initRootInfo().
static int copyContents (const shared_ptr< EncFS_Root > & rootInfo, const char * encfsName, const char * targetName) static
References processContents().
Referenced by traverseDirs().
static int copyLink (const struct stat & stBuf, const shared_ptr< EncFS_Root > & rootInfo, const string & cpath, const string & destName) static
Referenced by traverseDirs().
static int do_chpasswd (bool useStdin, int argc, char ** argv) static
References _, checkDir(), Config_None, Cipher::New(), readConfig(), and saveConfig().
Referenced by chpasswd(), and chpasswdAutomaticly().
static bool endsWith (const string & str, char ch) static
Referenced by traverseDirs().
static RootPtr initRootInfo (int & argc, char **& argv) static
References _, checkDir(), and initFS().
Referenced by cmd_cat(), cmd_decode(), cmd_encode(), cmd_export(), cmd_ls(), cmd_showcruft(), and cmd_showKey().
static RootPtr initRootInfo (const char * crootDir) static
References _, checkDir(), and initFS().
int main (int argc, char ** argv)
References _, commands, showInfo(), and usage().
template<typename T > int processContents (const shared_ptr< EncFS_Root > & rootInfo, const char * path, T & op)
Referenced by cmd_cat(), and copyContents().
int showcruft (const shared_ptr< EncFS_Root > & rootInfo, const char * dirName)
References _, isDirectory(), DirTraverse::nextInvalid(), DirTraverse::nextPlaintextName(), and DirTraverse::valid().
Referenced by cmd_showcruft().
static int showInfo (int argc, char ** argv) static
References _, checkDir(), Config_None, Config_Prehistoric, Config_V3, Config_V4, Config_V5, Config_V6, Config_YC, readConfig(), and showFSInfo().
Referenced by main().
static int showVersion (int argc, char ** argv) static
References _.
static int traverseDirs (const shared_ptr< EncFS_Root > & rootInfo, string volumeDir, string destDir) static
References copyContents(), copyLink(), endsWith(), DirTraverse::nextPlaintextName(), and DirTraverse::valid().
Referenced by cmd_export().
static void usage (const char * name) static
References _, CommandOpts::argStr, commands, gettext, and CommandOpts::name.
Referenced by main().
Variable Documentation
struct CommandOpts commands[]
Referenced by main(), and usage().