Youcrypt/EncFS: encfsTestBed.cpp File Reference
encfsTestBed.cpp File Reference
#include "encfs.h"
#include "config.h"
#include "autosprintf.h"
#include <iostream>
#include <string>
#include <sstream>
#include <cassert>
#include <cstdio>
#include <unistd.h>
#include <sys/time.h>
#include <cerrno>
#include <cstring>
#include <vector>
#include <getopt.h>
#include <boost/scoped_ptr.hpp>
#include <boost/shared_ptr.hpp>
#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>
#include <rlog/rlog.h>
#include <rlog/Error.h>
#include <rlog/RLogChannel.h>
#include <rlog/SyslogNode.h>
#include <rlog/StdioNode.h>
#include "ConfigReader.h"
#include "Interface.h"
#include "MemoryPool.h"
#include "FileUtils.h"
#include "DirNode.h"
#include "Context.h"
#include "openssl.h"
#include "YoucryptFolder.h"
#include "Credentials.h"
#include "PassphraseCredentials.h"
#include <locale.h>
#include "i18n.h"
Classes
struct EncFS_Args
Macros
#define fuse_unmount fuse_unmount_compat22
#define PUSHARG(ARG)
Functions
void fuse_unmount_compat22 (const char *mountpoint)
static int MAX (int a, int b)
static void usage (const char *name)
static void FuseUsage ()
static string slashTerminate (const string &src)
static std::vector< std::string > & split (const std::string &s, char delim, std::vector< std::string > &elems)
static std::vector< std::string > split (const std::string &s, char delim)
static bool processArgs (int argc, char *argv[], const shared_ptr< EncFS_Args > &out)
int main (int argc, char **argv)
Variables
const int MaxFuseArgs = 32
Macro Definition Documentation
#define fuse_unmount fuse_unmount_compat22
#define PUSHARG (ARG)
Value:
rAssert(out->fuseArgc < MaxFuseArgs); \
out->fuseArgv[out->fuseArgc++] = ARG
Referenced by processArgs().
Function Documentation
void fuse_unmount_compat22 (const char * mountpoint)
static void FuseUsage () static
References _.
Referenced by processArgs().
int main (int argc, char ** argv)
References MemoryPool::destroyAll(), youcrypt::YoucryptFolder::importContent(), MaxFuseArgs, openssl_init(), openssl_shutdown(), processArgs(), and usage().
static int MAX (int a, int b) inline static
static bool processArgs (int argc, char * argv[], const shared_ptr< EncFS_Args > & out) static
References _, Config_Paranoia, Config_Standard, FuseUsage(), isAbsolutePath(), isDirectory(), lastPathElement(), MaxFuseArgs, PUSHARG, slashTerminate(), split(), and userAllowMkdir().
Referenced by main().
static string slashTerminate (const string & src) static
Referenced by processArgs().
static std::vector<std::string>& split (const std::string & s, char delim, std::vector< std::string > & elems) static
Referenced by processArgs(), and split().
static std::vector<std::string> split (const std::string & s, char delim) static
References split().
static void usage (const char * name) static
References _.
Referenced by main().
Variable Documentation
const int MaxFuseArgs = 32
Referenced by main(), and processArgs().