Youcrypt/EncFS: encfs.cpp File Reference
encfs.cpp File Reference
#include "encfs.h"
#include <cstdio>
#include <cstring>
#include <unistd.h>
#include <fcntl.h>
#include <dirent.h>
#include <cerrno>
#include <sys/statvfs.h>
#include <sys/time.h>
#include <sys/types.h>
#include <string>
#include <map>
#include <boost/tuple/tuple.hpp>
#include <boost/scoped_array.hpp>
#include "DirNode.h"
#include "MemoryPool.h"
#include "FileUtils.h"
#include "Mutex.h"
#include "Context.h"
#include <rlog/rlog.h>
#include <rlog/Error.h>
Macros
#define MIN(a, b) (((a)<(b)) ? (a): (b))
#define ESUCCESS 0
#define GET_FN(ctx, finfo) ctx->getNode((void*)(uintptr_t)finfo->fh)
Functions
static EncFS_Context * context ()
template<typename T >
static int withCipherPath (const char *opName, const char *path, int(*op)(EncFS_Context *, const string &name, T data), T data, bool passReturnCode=false)
template<typename T >
static int withFileNode (const char *opName, const char *path, struct fuse_file_info *fi, int(*op)(FileNode *, T data), T data)
int _do_getattr (FileNode *fnode, struct stat *stbuf)
int encfs_getattr (const char *path, struct stat *stbuf)
int encfs_fgetattr (const char *path, struct stat *stbuf, struct fuse_file_info *fi)
int encfs_getdir (const char *path, fuse_dirh_t h, fuse_dirfil_t filler)
int encfs_mknod (const char *path, mode_t mode, dev_t rdev)
int encfs_mkdir (const char *path, mode_t mode)
int encfs_unlink (const char *path)
int _do_rmdir (EncFS_Context *, const string &cipherPath, int)
int encfs_rmdir (const char *path)
int _do_readlink (EncFS_Context *ctx, const string &cyName, tuple< char *, size_t > data)
int encfs_readlink (const char *path, char *buf, size_t size)
int encfs_symlink (const char *from, const char *to)
int encfs_link (const char *from, const char *to)
int encfs_rename (const char *from, const char *to)
int _do_chmod (EncFS_Context *, const string &cipherPath, mode_t mode)
int encfs_chmod (const char *path, mode_t mode)
int _do_chown (EncFS_Context *, const string &cyName, tuple< uid_t, gid_t > data)
int encfs_chown (const char *path, uid_t uid, gid_t gid)
int _do_truncate (FileNode *fnode, off_t size)
int encfs_truncate (const char *path, off_t size)
int encfs_ftruncate (const char *path, off_t size, struct fuse_file_info *fi)
int _do_utime (EncFS_Context *, const string &cyName, struct utimbuf *buf)
int encfs_utime (const char *path, struct utimbuf *buf)
int _do_utimens (EncFS_Context *, const string &cyName, const struct timespec ts[2])
int encfs_utimens (const char *path, const struct timespec ts[2])
int encfs_open (const char *path, struct fuse_file_info *file)
int _do_flush (FileNode *fnode, int)
int encfs_flush (const char *path, struct fuse_file_info *fi)
int encfs_release (const char *path, struct fuse_file_info *finfo)
int _do_read (FileNode *fnode, tuple< unsigned char *, size_t, off_t > data)
int encfs_read (const char *path, char *buf, size_t size, off_t offset, struct fuse_file_info *file)
int _do_fsync (FileNode *fnode, int dataSync)
int encfs_fsync (const char *path, int dataSync, struct fuse_file_info *file)
int _do_write (FileNode *fnode, tuple< const char *, size_t, off_t > data)
int encfs_write (const char *path, const char *buf, size_t size, off_t offset, struct fuse_file_info *file)
int encfs_statfs (const char *path, struct statvfs *st)
Variables
static RLogChannel * Info = DEF_CHANNEL("info", Log_Info)
Macro Definition Documentation
#define ESUCCESS 0
Referenced by _do_chown(), _do_getattr(), _do_readlink(), _do_utime(), _do_utimens(), encfs_getdir(), encfs_open(), encfs_release(), encfs_symlink(), and withCipherPath().
#define GET_FN (ctx, finfo) ctx->getNode((void*)(uintptr_t)finfo->fh)
Referenced by withFileNode().
#define MIN (a, b) (((a)<(b)) ? (a): (b))
Referenced by BytesToKey(), flipBytes(), and ConfigVar::read().
Function Documentation
int _do_chmod (EncFS_Context * , const string & cipherPath, mode_t mode)
Referenced by encfs_chmod().
int _do_chown (EncFS_Context * , const string & cyName, tuple< uid_t, gid_t > data)
References ESUCCESS.
Referenced by encfs_chown().
int _do_flush (FileNode * fnode, int)
References FileNode::open().
Referenced by encfs_flush().
int _do_fsync (FileNode * fnode, int dataSync)
References FileNode::sync().
Referenced by encfs_fsync().
int _do_getattr (FileNode * fnode, struct stat * stbuf)
References FileNode::cipherName(), context(), ESUCCESS, FileNode::getAttr(), and EncFS_Context::getRoot().
Referenced by encfs_fgetattr(), and encfs_getattr().
int _do_read (FileNode * fnode, tuple< unsigned char *, size_t, off_t > data)
References FileNode::read().
Referenced by encfs_read().
int _do_readlink (EncFS_Context * ctx, const string & cyName, tuple< char *, size_t > data)
References ESUCCESS, and EncFS_Context::getRoot().
Referenced by encfs_readlink().
int _do_rmdir (EncFS_Context * , const string & cipherPath, int)
Referenced by encfs_rmdir().
int _do_truncate (FileNode * fnode, off_t size)
References FileNode::truncate().
Referenced by encfs_ftruncate(), and encfs_truncate().
int _do_utime (EncFS_Context * , const string & cyName, struct utimbuf * buf)
References ESUCCESS.
Referenced by encfs_utime().
int _do_utimens (EncFS_Context * , const string & cyName, const struct timespec ts[2])
References ESUCCESS.
Referenced by encfs_utimens().
int _do_write (FileNode * fnode, tuple< const char *, size_t, off_t > data)
References FileNode::write().
Referenced by encfs_write().
static EncFS_Context* context () static
Referenced by _do_getattr(), encfs_getdir(), encfs_link(), encfs_mkdir(), encfs_mknod(), encfs_open(), encfs_release(), encfs_rename(), encfs_statfs(), encfs_symlink(), encfs_unlink(), withCipherPath(), and withFileNode().
int encfs_chmod (const char * path, mode_t mode)
References _do_chmod(), and withCipherPath().
Referenced by main().
int encfs_chown (const char * path, uid_t uid, gid_t gid)
References _do_chown(), and withCipherPath().
Referenced by main().
int encfs_fgetattr (const char * path, struct stat * stbuf, struct fuse_file_info * fi)
References _do_getattr(), and withFileNode().
Referenced by main().
int encfs_flush (const char * path, struct fuse_file_info * fi)
References _do_flush(), and withFileNode().
Referenced by main().
int encfs_fsync (const char * path, int dataSync, struct fuse_file_info * file)
References _do_fsync(), and withFileNode().
Referenced by main().
int encfs_ftruncate (const char * path, off_t size, struct fuse_file_info * fi)
References _do_truncate(), and withFileNode().
Referenced by main().
int encfs_getattr (const char * path, struct stat * stbuf)
References _do_getattr(), and withFileNode().
Referenced by main().
int encfs_getdir (const char * path, fuse_dirh_t h, fuse_dirfil_t filler)
References context(), ESUCCESS, EncFS_Context::getRoot(), Info, DirTraverse::nextPlaintextName(), and DirTraverse::valid().
Referenced by main().
int encfs_link (const char * from, const char * to)
References context(), and EncFS_Context::getRoot().
Referenced by main().
int encfs_mkdir (const char * path, mode_t mode)
References context(), EncFS_Context::getRoot(), parentDirectory(), and EncFS_Context::publicFilesystem.
Referenced by main().
int encfs_mknod (const char * path, mode_t mode, dev_t rdev)
References context(), EncFS_Context::getRoot(), Info, and EncFS_Context::publicFilesystem.
Referenced by main().
int encfs_open (const char * path, struct fuse_file_info * file)
References context(), ESUCCESS, EncFS_Context::getRoot(), Info, and EncFS_Context::putNode().
Referenced by main().
int encfs_read (const char * path, char * buf, size_t size, off_t offset, struct fuse_file_info * file)
References _do_read(), and withFileNode().
Referenced by main().
int encfs_readlink (const char * path, char * buf, size_t size)
References _do_readlink(), and withCipherPath().
Referenced by main().
int encfs_release (const char * path, struct fuse_file_info * finfo)
References context(), EncFS_Context::eraseNode(), and ESUCCESS.
Referenced by main().
int encfs_rename (const char * from, const char * to)
References context(), and EncFS_Context::getRoot().
Referenced by main().
int encfs_rmdir (const char * path)
References _do_rmdir(), and withCipherPath().
Referenced by main().
int encfs_statfs (const char * path, struct statvfs * st)
References context(), Info, and EncFS_Context::rootCipherDir.
Referenced by main().
int encfs_symlink (const char * from, const char * to)
References context(), ESUCCESS, EncFS_Context::getRoot(), Info, EncFS_Context::publicFilesystem, setfsgid(), and setfsuid().
Referenced by main().
int encfs_truncate (const char * path, off_t size)
References _do_truncate(), and withFileNode().
Referenced by main().
int encfs_unlink (const char * path)
References context(), and EncFS_Context::getRoot().
Referenced by main().
int encfs_utime (const char * path, struct utimbuf * buf)
References _do_utime(), and withCipherPath().
Referenced by main().
int encfs_utimens (const char * path, const struct timespec ts[2])
References _do_utimens(), and withCipherPath().
Referenced by main().
int encfs_write (const char * path, const char * buf, size_t size, off_t offset, struct fuse_file_info * file)
References _do_write(), and withFileNode().
Referenced by main().
template<typename T > static int withCipherPath (const char * opName, const char * path, int(*)(EncFS_Context *, const string &name, T data) op, T data, bool passReturnCode = false) static
References context(), ESUCCESS, EncFS_Context::getRoot(), and Info.
Referenced by encfs_chmod(), encfs_chown(), encfs_readlink(), encfs_rmdir(), encfs_utime(), and encfs_utimens().
template<typename T > static int withFileNode (const char * opName, const char * path, struct fuse_file_info * fi, int(*)(FileNode *, T data) op, T data) static
References context(), GET_FN, EncFS_Context::getRoot(), and Info.
Referenced by encfs_fgetattr(), encfs_flush(), encfs_fsync(), encfs_ftruncate(), encfs_getattr(), encfs_read(), encfs_truncate(), and encfs_write().
Variable Documentation
RLogChannel* Info = DEF_CHANNEL("info", Log_Info) static
Referenced by encfs_getdir(), encfs_mknod(), encfs_open(), encfs_statfs(), encfs_symlink(), withCipherPath(), and withFileNode().