Youcrypt/EncFS: main.cpp File Reference
main.cpp File Reference
#include "encfs.h"
#include "config.h"
#include "autosprintf.h"
#include <iostream>
#include <string>
#include <sstream>
#include <cassert>
#include <cstdio>
#include <unistd.h>
#include <sys/time.h>
#include <cerrno>
#include <cstring>
#include <vector>
#include <getopt.h>
#include <boost/scoped_ptr.hpp>
#include <boost/shared_ptr.hpp>
#include <rlog/rlog.h>
#include <rlog/Error.h>
#include <rlog/RLogChannel.h>
#include <rlog/SyslogNode.h>
#include <rlog/StdioNode.h>
#include "ConfigReader.h"
#include "Interface.h"
#include "MemoryPool.h"
#include "FileUtils.h"
#include "DirNode.h"
#include "Context.h"
#include "openssl.h"
#include <locale.h>
#include "i18n.h"
Classes
struct EncFS_Args
Macros
#define fuse_unmount fuse_unmount_compat22
#define PUSHARG(ARG)
Functions
void fuse_unmount_compat22 (const char *mountpoint)
static int MAX (int a, int b)
static void usage (const char *name)
static void FuseUsage ()
static string slashTerminate (const string &src)
static std::vector< std::string > & split (const std::string &s, char delim, std::vector< std::string > &elems)
static std::vector< std::string > split (const std::string &s, char delim)
static bool processArgs (int argc, char *argv[], const shared_ptr< EncFS_Args > &out)
static void * idleMonitor (void *)
void * encfs_init (fuse_conn_info *conn)
void encfs_destroy (void *_ctx)
void read_fully (int fd, char *ptr, size_t size)
int parse_sock_args (int client_socket_fd, char ***pargv)
int main (int argc, char **argv)
static bool unmountFS (EncFS_Context *ctx)
Variables
const int MaxFuseArgs = 32
static int oldStderr = STDERR_FILENO
const int ActivityCheckInterval = 10
Macro Definition Documentation
#define fuse_unmount fuse_unmount_compat22
Referenced by unmountFS().
#define PUSHARG (ARG)
Value:
rAssert(out->fuseArgc < MaxFuseArgs); \
out->fuseArgv[out->fuseArgc++] = ARG
Referenced by processArgs().
Function Documentation
void encfs_destroy (void * _ctx)
References EncFS_Context::args, EncFS_Context::monitorThread, EncFS_Context::running, EncFS_Context::wakeupCond, and EncFS_Context::wakeupMutex.
void* encfs_init (fuse_conn_info * conn)
References EncFS_Context::args, idleMonitor(), EncFS_Context::monitorThread, oldStderr, and EncFS_Context::running.
void fuse_unmount_compat22 (const char * mountpoint)
static void FuseUsage () static
References _.
Referenced by processArgs().
static void * idleMonitor (void * _arg) static
References ActivityCheckInterval, EncFS_Context::args, EncFS_Context::getAndResetUsageCounter(), EncFS_Context::isMounted(), EncFS_Context::openFileCount(), EncFS_Context::running, unmountFS(), usage(), EncFS_Context::wakeupCond, and EncFS_Context::wakeupMutex.
Referenced by encfs_init().
int main (int argc, char ** argv)
References _, EncFS_Context::args, MemoryPool::destroyAll(), encfs_chmod(), encfs_chown(), encfs_destroy(), encfs_fgetattr(), encfs_flush(), encfs_fsync(), encfs_ftruncate(), encfs_getattr(), encfs_getdir(), encfs_init(), encfs_link(), encfs_mkdir(), encfs_mknod(), encfs_open(), encfs_read(), encfs_readlink(), encfs_release(), encfs_rename(), encfs_rmdir(), encfs_statfs(), encfs_symlink(), encfs_truncate(), encfs_unlink(), encfs_utime(), encfs_utimens(), encfs_write(), initFS(), MaxFuseArgs, oldStderr, openssl_init(), openssl_shutdown(), EncFS_Context::opts, parse_sock_args(), processArgs(), EncFS_Context::publicFilesystem, EncFS_Context::setRoot(), and usage().
static int MAX (int a, int b) inline static
int parse_sock_args (int client_socket_fd, char *** pargv)
static bool processArgs (int argc, char * argv[], const shared_ptr< EncFS_Args > & out) static
References _, Config_Paranoia, Config_Standard, FuseUsage(), isAbsolutePath(), isDirectory(), lastPathElement(), MaxFuseArgs, PUSHARG, slashTerminate(), split(), and userAllowMkdir().
Referenced by main().
void read_fully (int fd, char * ptr, size_t size)
static string slashTerminate (const string & src) static
Referenced by processArgs().
static std::vector<std::string>& split (const std::string & s, char delim, std::vector< std::string > & elems) static
static std::vector<std::string> split (const std::string & s, char delim) static
References split().
static bool unmountFS (EncFS_Context * ctx) static
References _, EncFS_Context::args, fuse_unmount, and EncFS_Context::setRoot().
Referenced by idleMonitor().
static void usage (const char * name) static
References _.
Referenced by idleMonitor(), and main().
Variable Documentation
const int ActivityCheckInterval = 10
const int MaxFuseArgs = 32
int oldStderr = STDERR_FILENO static
Referenced by encfs_init(), and main().