Youcrypt/EncFS: makeKey.cpp File Reference
makeKey.cpp File Reference
#include "encfs.h"
#include "Cipher.h"
#include "CipherKey.h"
#include "openssl.h"
#include <iostream>
#include <sys/types.h>
#include <unistd.h>
Functions
void genKey (const shared_ptr< Cipher > &cipher)
int main (int argc, char **argv)
Function Documentation
void genKey (const shared_ptr< Cipher > & cipher)
Referenced by main().
int main (int argc, char ** argv)
References genKey(), Cipher::New(), and openssl_init().