Youcrypt/EncFS: MemoryPool Namespace Reference
MemoryPool Namespace Reference
Functions
MemBlock allocate (int size)
void release (const MemBlock &el)
void destroyAll ()
Function Documentation
MemBlock MemoryPool::allocate (int size)
References allocBlock(), BLOCKDATA, MemBlock::data, gMemPool, gMPoolMutex, MemBlock::internalData, BlockList::next, BlockList::size, and VALGRIND_MAKE_MEM_UNDEFINED.
Referenced by checkErrorPropogation(), BlockFileIO::padFile(), BlockFileIO::read(), MACFileIO::readOneBlock(), BlockFileIO::truncate(), BlockFileIO::write(), and MACFileIO::writeOneBlock().
void MemoryPool::destroyAll ()
References freeBlock(), gMemPool, gMPoolMutex, and BlockList::next.
Referenced by main().
void MemoryPool::release (const MemBlock & el)
References BLOCKDATA, BlockList::data, gMemPool, gMPoolMutex, MemBlock::internalData, BlockList::next, BlockList::size, VALGRIND_MAKE_MEM_NOACCESS, and VALGRIND_MAKE_MEM_UNDEFINED.
Referenced by checkErrorPropogation(), BlockFileIO::padFile(), BlockFileIO::read(), MACFileIO::readOneBlock(), BlockFileIO::truncate(), BlockFileIO::write(), and MACFileIO::writeOneBlock().