Youcrypt/EncFS: boost::serialization Namespace Reference
boost::serialization Namespace Reference
Functions
template<class Archive >
void save (Archive &ar, const EncFSConfig &cfg, unsigned int version)
template<class Archive >
void load (Archive &ar, EncFSConfig &cfg, unsigned int version)
template<class Archive >
void serialize (Archive &ar, EncFSConfig &cfg, unsigned int version)
template<class Archive >
void serialize (Archive &ar, Interface &i, const unsigned int version)
Function Documentation
template<class Archive > void boost::serialization::load (Archive & ar, EncFSConfig & cfg, unsigned int version)
References EncFSConfig::allowHoles, EncFSConfig::assignKeyData(), EncFSConfig::assignSaltData(), EncFSConfig::blockMACBytes, EncFSConfig::blockMACRandBytes, EncFSConfig::blockSize, EncFSConfig::chainedNameIV, EncFSConfig::cipherIface, EncFSConfig::creator, EncFSConfig::desiredKDFDuration, EncFSConfig::easyencKeys, EncFSConfig::easyencNumUsers, EncFSConfig::externalIVChaining, EncFSConfig::getCipher(), EncFSConfig::ignoreList, EncFSConfig::kdfIterations, EncFSConfig::keySize, EncFSConfig::nameIface, NormalKDFDuration, EncFSConfig::salt, EncFSConfig::subVersion, EncFSConfig::uniqueIV, and V5SubVersion.
template<class Archive > void boost::serialization::save (Archive & ar, const EncFSConfig & cfg, unsigned int version)
References EncFSConfig::allowHoles, EncFSConfig::blockMACBytes, EncFSConfig::blockMACRandBytes, EncFSConfig::blockSize, EncFSConfig::chainedNameIV, EncFSConfig::cipherIface, EncFSConfig::creator, EncFSConfig::desiredKDFDuration, EncFSConfig::easyencKeys, EncFSConfig::easyencNumUsers, EncFSConfig::externalIVChaining, EncFSConfig::getKeyData(), EncFSConfig::getSaltData(), EncFSConfig::ignoreList, EncFSConfig::kdfIterations, EncFSConfig::keyData, EncFSConfig::keySize, EncFSConfig::nameIface, EncFSConfig::salt, EncFSConfig::subVersion, EncFSConfig::uniqueIV, and V6SubVersion.
template<class Archive > void boost::serialization::serialize (Archive & ar, EncFSConfig & cfg, unsigned int version)
template<class Archive > void boost::serialization::serialize (Archive & ar, Interface & i, const unsigned int version)
References rel::Interface::current(), rel::Interface::name(), and rel::Interface::revision().