Youcrypt/EncFS: openssl.cpp File Reference
openssl.cpp File Reference
#include "openssl.h"
#include <pthread.h>
#include <rlog/rlog.h>
#include <openssl/ssl.h>
#include <openssl/rand.h>
#include <openssl/engine.h>
Macros
#define NO_DES
Functions
unsigned long pthreads_thread_id ()
void pthreads_locking_callback (int mode, int n, const char *caller_file, int caller_line)
void pthreads_locking_cleanup ()
void openssl_init (bool threaded)
void openssl_shutdown (bool threaded)
Variables
static pthread_mutex_t * crypto_locks = NULL
Macro Definition Documentation
#define NO_DES
Function Documentation
void openssl_init (bool threaded)
References pthreads_locking_callback(), and pthreads_thread_id().
Referenced by main().
void openssl_shutdown (bool threaded)
References pthreads_locking_cleanup().
Referenced by main().
void pthreads_locking_callback (int mode, int n, const char * caller_file, int caller_line)
References crypto_locks.
Referenced by openssl_init().
void pthreads_locking_cleanup ()
References crypto_locks.
Referenced by openssl_shutdown().
unsigned long pthreads_thread_id ()
Referenced by openssl_init().
Variable Documentation
pthread_mutex_t* crypto_locks = NULL static
Referenced by pthreads_locking_callback(), and pthreads_locking_cleanup().