Youcrypt/EncFS: openssl.h File Reference
openssl.h File Reference
Functions
void openssl_init (bool isThreaded)
void openssl_shutdown (bool isThreaded)
Function Documentation
void openssl_init (bool isThreaded)
References pthreads_locking_callback(), and pthreads_thread_id().
Referenced by main().
void openssl_shutdown (bool isThreaded)
References pthreads_locking_cleanup().
Referenced by main().