Youcrypt/EncFS: readpassphrase.cpp File Reference
readpassphrase.cpp File Reference
#include <csignal>
#include <cstdio>
#include <cerrno>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <paths.h>
#include <cstring>
#include <cctype>
#include <termios.h>
#include <readpassphrase.h>
Macros
#define _T_FLUSH (TCSAFLUSH)
Functions
static void handler (int)
char * readpassphrase (const char *prompt, char *buf, size_t bufsiz, int flags)
Variables
static volatile sig_atomic_t signo
Macro Definition Documentation
#define _T_FLUSH (TCSAFLUSH)
Referenced by readpassphrase().
Function Documentation
static void handler (int s) static
References signo.
Referenced by readpassphrase().
char* readpassphrase (const char * prompt, char * buf, size_t bufsiz, int flags)
References _T_FLUSH, handler(), RPP_ECHO_ON, RPP_FORCELOWER, RPP_FORCEUPPER, RPP_REQUIRE_TTY, RPP_SEVENBIT, and signo.
Referenced by EncFSConfig::getNewUserKey(), and EncFSConfig::getUserKey().
Variable Documentation
volatile sig_atomic_t signo static
Referenced by handler(), and readpassphrase().