Youcrypt/EncFS: test.cpp File Reference
test.cpp File Reference
#include "encfs.h"
#include "config.h"
#include <iostream>
#include <cstdlib>
#include <sstream>
#include "Cipher.h"
#include "DirNode.h"
#include "MemoryPool.h"
#include "Interface.h"
#include "FileUtils.h"
#include "StreamNameIO.h"
#include "BlockNameIO.h"
#include "NullNameIO.h"
#include <rlog/rlog.h>
#include <rlog/Error.h>
#include <rlog/StdioNode.h>
#include <rlog/RLogChannel.h>
Functions
static int checkErrorPropogation (const shared_ptr< Cipher > &cipher, int size, int byteToChange, const CipherKey &key)
static bool testNameCoding (DirNode &dirNode, bool verbose)
bool runTests (const shared_ptr< Cipher > &cipher, bool verbose)
int main (int argc, char *argv[])
Variables
const int FSBlockSize = 256
const char TEST_ROOTDIR [] = "/foo"
Function Documentation
static int checkErrorPropogation (const shared_ptr< Cipher > & cipher, int size, int byteToChange, const CipherKey & key) static
References MemoryPool::allocate(), MemBlock::data, FSBlockSize, and MemoryPool::release().
Referenced by runTests().
int main (int argc, char * argv[])
References MemoryPool::destroyAll(), FSBlockSize, Cipher::GetAlgorithmList(), Cipher::New(), and runTests().
bool runTests (const shared_ptr< Cipher > & cipher, bool verbose)
References EncFSConfig::assignKeyData(), EncFSConfig::blockSize, checkErrorPropogation(), EncFSConfig::cipherIface, StreamNameIO::CurrentInterface(), BlockNameIO::CurrentInterface(), FSBlockSize, EncFSConfig::getKeyData(), rel::Interface::implements(), EncFSConfig::keySize, TEST_ROOTDIR, and testNameCoding().
Referenced by main().
static bool testNameCoding (DirNode & dirNode, bool verbose) static
References DirNode::plainPath(), and DirNode::relativeCipherPath().
Referenced by runTests().
Variable Documentation
const int FSBlockSize = 256
Referenced by checkErrorPropogation(), main(), and runTests().
const char TEST_ROOTDIR[] = "/foo"
Referenced by runTests().